/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function b(h){h=String(h);return h.charAt(0).toUpperCase()+h.slice(1)}function g(h,H){var p=-1,x=h?h.length:0;if("number"==typeof x&&-1<x&&x<=C)for(;++p<x;)H(h[p],p,h);else m(h,H)}function d(h){h=String(h).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(h)?h:b(h)}function m(h,H){for(var p in h)E.call(h,p)&&H(h[p],p,h)}function l(h){return null==h?b(h):v.call(h).slice(8,-1)}function q(h,H){var p=null!=h?typeof h[H]:"number";return!/^(?:boolean|number|string|undefined)$/.test(p)&&
("object"==p?!!h[H]:!0)}function e(h){return String(h).replace(/([ -])(?!$)/g,"$1?")}function r(h,H){var p=null;g(h,function(x,f){p=H(p,x,f,h)});return p}function k(h){function H(S){return r(S,function(N,L){var V=L.pattern||e(L);!N&&(N=RegExp("\\b"+V+" *\\d+[.\\w_]*","i").exec(h)||RegExp("\\b"+V+" *\\w+-[\\w]*","i").exec(h)||RegExp("\\b"+V+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(h))&&((N=String(L.label&&!RegExp(V,"i").test(L.label)?L.label:N).split("/"))[1]&&!/[\d.]+/.test(N[0])&&(N[0]+=
" "+N[1]),L=L.label||L,N=d(N[0].replace(RegExp(V,"i"),L).replace(RegExp("; *(?:"+L+"[_-])?","i")," ").replace(RegExp("("+L+")[-_.]?(\\w)","i"),"$1 $2")));return N})}function p(S){return r(S,function(N,L){return N||(RegExp(L+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(h)||0)[1]||null})}var x=u,f=h&&"object"==typeof h&&"String"!=l(h);f&&(x=h,h=null);var z=x.navigator||{},n=z.userAgent||"";h||(h=n);var w=f?!!z.likeChrome:/\bChrome\b/.test(h)&&!/internal|\n/i.test(v.toString()),
M=f?"Object":"ScriptBridgingProxyObject",G=f?"Object":"Environment",O=f&&x.java?"JavaPackage":l(x.java),P=f?"Object":"RuntimeObject";G=(O=/\bJava/.test(O)&&x.java)&&l(x.environment)==G;var U=O?"a":"\u03b1",T=O?"b":"\u03b2",W=x.document||{},Q=x.operamini||x.opera,Z=F.test(Z=f&&Q?Q["[[Class]]"]:l(Q))?Z:Q=null,a,I=h;f=[];var Y=null,R=h==n;n=R&&Q&&"function"==typeof Q.version&&Q.version();var J=function(S){return r(S,function(N,L){return N||RegExp("\\b"+(L.pattern||e(L))+"\\b","i").exec(h)&&(L.label||
L)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),y=function(S){return r(S,function(N,L){return N||RegExp("\\b"+(L.pattern||e(L))+"\\b","i").exec(h)&&(L.label||L)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),K=H([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),X=function(S){return r(S,function(N,L,V){return N||(L[K]||L[/^[a-z]+(?: +[a-z]+\b)*/i.exec(K)]||RegExp("\\b"+e(V)+"(?:\\b|\\w*\\d)","i").exec(h))&&V})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),B=function(S){return r(S,function(N,L){var V=L.pattern||e(L);if(!N&&(N=RegExp("\\b"+V+"(?:/[\\d.]+|[ \\w.]*)","i").exec(h))){var aa=N,ba=L.label||L,ca={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};V&&ba&&/^Win/i.test(aa)&&!/^Windows Phone /i.test(aa)&&(ca=ca[/[\d.]+$/.exec(aa)])&&(aa="Windows "+ca);aa=String(aa);V&&ba&&(aa=aa.replace(RegExp(V,"i"),ba));N=aa=d(aa.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return N})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);J&&(J=[J]);X&&!K&&(K=H([X]));if(a=/\bGoogle TV\b/.exec(K))K=a[0];/\bSimulator\b/i.test(h)&&(K=(K?K+" ":"")+"Simulator");"Opera Mini"==y&&/\bOPiOS\b/.test(h)&&f.push("running in Turbo/Uncompressed mode");"IE"==y&&/\blike iPhone OS\b/.test(h)?(a=k(h.replace(/like iPhone OS/,"")),X=a.manufacturer,K=a.product):/^iP/.test(K)?(y||(y="Safari"),B="iOS"+((a=/ OS ([\d_]+)/i.exec(h))?" "+a[1].replace(/_/g,"."):"")):"Konqueror"!=y||/buntu/i.test(B)?X&&"Google"!=X&&
(/Chrome/.test(y)&&!/\bMobile Safari\b/i.test(h)||/\bVita\b/.test(K))||/\bAndroid\b/.test(B)&&/^Chrome/.test(y)&&/\bVersion\//i.test(h)?(y="Android Browser",B=/\bAndroid\b/.test(B)?B:"Android"):"Silk"==y?(/\bMobi/i.test(h)||(B="Android",f.unshift("desktop mode")),/Accelerated *= *true/i.test(h)&&f.unshift("accelerated")):"PaleMoon"==y&&(a=/\bFirefox\/([\d.]+)\b/.exec(h))?f.push("identifying as Firefox "+a[1]):"Firefox"==y&&(a=/\b(Mobile|Tablet|TV)\b/i.exec(h))?(B||(B="Firefox OS"),K||(K=a[1])):!y||
(a=!/\bMinefield\b/i.test(h)&&/\b(?:Firefox|Safari)\b/.exec(y))?(y&&!K&&/[\/,]|^[^(]+?\)/.test(h.slice(h.indexOf(a+"/")+8))&&(y=null),(a=K||X||B)&&(K||X||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(B))&&(y=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(B)?B:a)+" Browser")):"Electron"==y&&(a=(/\bChrome\/([\d.]+)\b/.exec(h)||0)[1])&&f.push("Chromium "+a):B="Kubuntu";n||(n=p(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",e(y),
"(?:Firefox|Minefield|NetFront)"]));if(a="iCab"==J&&3<parseFloat(n)&&"WebKit"||/\bOpera\b/.test(y)&&(/\bOPR\b/.test(h)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(h)&&!/^(?:Trident|EdgeHTML)$/.test(J)&&"WebKit"||!J&&/\bMSIE\b/i.test(h)&&("Mac OS"==B?"Tasman":"Trident")||"WebKit"==J&&/\bPlayStation\b(?! Vita\b)/i.test(y)&&"NetFront")J=[a];"IE"==y&&(a=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(h)||0)[1])?(y+=" Mobile",B="Windows Phone "+(/\+$/.test(a)?a:a+".x"),f.unshift("desktop mode")):/\bWPDesktop\b/i.test(h)?
(y="IE Mobile",B="Windows Phone 8.x",f.unshift("desktop mode"),n||(n=(/\brv:([\d.]+)/.exec(h)||0)[1])):"IE"!=y&&"Trident"==J&&(a=/\brv:([\d.]+)/.exec(h))&&(y&&f.push("identifying as "+y+(n?" "+n:"")),y="IE",n=a[1]);if(R){if(q(x,"global"))if(O&&(a=O.lang.System,I=a.getProperty("os.arch"),B=B||a.getProperty("os.name")+" "+a.getProperty("os.version")),G){try{n=x.require("ringo/engine").version.join("."),y="RingoJS"}catch(S){(a=x.system)&&a.global.system==x.system&&(y="Narwhal",B||(B=a[0].os||null))}y||
(y="Rhino")}else"object"==typeof x.process&&!x.process.browser&&(a=x.process)&&("object"==typeof a.versions&&("string"==typeof a.versions.electron?(f.push("Node "+a.versions.node),y="Electron",n=a.versions.electron):"string"==typeof a.versions.nw&&(f.push("Chromium "+n,"Node "+a.versions.node),y="NW.js",n=a.versions.nw)),y||(y="Node.js",I=a.arch,B=a.platform,n=(n=/[\d.]+/.exec(a.version))?n[0]:null));else l(a=x.runtime)==M?(y="Adobe AIR",B=a.flash.system.Capabilities.os):l(a=x.phantom)==P?(y="PhantomJS",
n=(a=a.version||null)&&a.major+"."+a.minor+"."+a.patch):"number"==typeof W.documentMode&&(a=/\bTrident\/(\d+)/i.exec(h))?(n=[n,W.documentMode],(a=+a[1]+4)!=n[1]&&(f.push("IE "+n[1]+" mode"),J&&(J[1]=""),n[1]=a),n="IE"==y?String(n[1].toFixed(1)):n[0]):"number"==typeof W.documentMode&&/^(?:Chrome|Firefox)\b/.test(y)&&(f.push("masking as "+y+" "+n),y="IE",n="11.0",J=["Trident"],B="Windows");B=B&&d(B)}n&&(a=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(n)||/(?:alpha|beta)(?: ?\d)?/i.exec(h+";"+(R&&z.appMinorVersion))||
/\bMinefield\b/i.test(h)&&"a")&&(Y=/b/i.test(a)?"beta":"alpha",n=n.replace(RegExp(a+"\\+?$"),"")+("beta"==Y?T:U)+(/\d+\+?/.exec(a)||""));if("Fennec"==y||"Firefox"==y&&/\b(?:Android|Firefox OS)\b/.test(B))y="Firefox Mobile";else if("Maxthon"==y&&n)n=n.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(K))"Xbox 360"==K&&(B=null),"Xbox 360"==K&&/\bIEMobile\b/.test(h)&&f.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(y)&&(!y||K||/Browser|Mobi/.test(y))||"Windows CE"!=B&&!/Mobi/i.test(h))if("IE"==
y&&R)try{null===x.external&&f.unshift("platform preview")}catch(S){f.unshift("embedded")}else(/\bBlackBerry\b/.test(K)||/\bBB10\b/.test(h))&&(a=(RegExp(K.replace(/ +/g," *")+"/([.\\d]+)","i").exec(h)||0)[1]||n)?(a=[a,/BB10/.test(h)],B=(a[1]?(K=null,X="BlackBerry"):"Device Software")+" "+a[0],n=null):this!=m&&"Wii"!=K&&(R&&Q||/Opera/.test(y)&&/\b(?:MSIE|Firefox)\b/i.test(h)||"Firefox"==y&&/\bOS X (?:\d+\.){2,}/.test(B)||"IE"==y&&(B&&!/^Win/.test(B)&&5.5<n||/\bWindows XP\b/.test(B)&&8<n||8==n&&!/\bTrident\b/.test(h)))&&
!F.test(a=k.call(m,h.replace(F,"")+";"))&&a.name&&(a="ing as "+a.name+((a=a.version)?" "+a:""),F.test(y)?(/\bIE\b/.test(a)&&"Mac OS"==B&&(B=null),a="identify"+a):(a="mask"+a,y=Z?d(Z.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(a)&&(B=null),R||(n=null)),J=["Presto"],f.push(a));else y+=" Mobile";if(a=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(h)||0)[1]){a=[parseFloat(a.replace(/\.(\d)$/,".0$1")),a];if("Safari"==y&&"+"==a[1].slice(-1))y="WebKit Nightly",Y="alpha",n=a[1].slice(0,-1);else if(n==
a[1]||n==(a[2]=(/\bSafari\/([\d.]+\+?)/i.exec(h)||0)[1]))n=null;a[1]=(/\bChrome\/([\d.]+)/i.exec(h)||0)[1];537.36==a[0]&&537.36==a[2]&&28<=parseFloat(a[1])&&"WebKit"==J&&(J=["Blink"]);R&&(w||a[1])?(J&&(J[1]="like Chrome"),a=a[1]||(a=a[0],530>a?1:532>a?2:532.05>a?3:533>a?4:534.03>a?5:534.07>a?6:534.1>a?7:534.13>a?8:534.16>a?9:534.24>a?10:534.3>a?11:535.01>a?12:535.02>a?"13+":535.07>a?15:535.11>a?16:535.19>a?17:536.05>a?18:536.1>a?19:537.01>a?20:537.11>a?"21+":537.13>a?23:537.18>a?24:537.24>a?25:537.36>
a?26:"Blink"!=J?"27":"28")):(J&&(J[1]="like Safari"),a=(a=a[0],400>a?1:500>a?2:526>a?3:533>a?4:534>a?"4+":535>a?5:537>a?6:538>a?7:601>a?8:"8"));J&&(J[1]+=" "+(a+="number"==typeof a?".x":/[.+]/.test(a)?"":"+"));"Safari"==y&&(!n||45<parseInt(n))&&(n=a)}"Opera"==y&&(a=/\bzbov|zvav$/.exec(B))?(y+=" ",f.unshift("desktop mode"),"zvav"==a?(y+="Mini",n=null):y+="Mobile",B=B.replace(RegExp(" *"+a+"$"),"")):"Safari"==y&&/\bChrome\b/.exec(J&&J[1])&&(f.unshift("desktop mode"),y="Chrome Mobile",n=null,/\bOS X\b/.test(B)?
(X="Apple",B="iOS 4.3+"):B=null);n&&0==n.indexOf(a=/[\d.]+$/.exec(B))&&-1<h.indexOf("/"+a+"-")&&(B=String(B.replace(a,"")).replace(/^ +| +$/g,""));J&&!/\b(?:Avant|Nook)\b/.test(y)&&(/Browser|Lunascape|Maxthon/.test(y)||"Safari"!=y&&/^iOS/.test(B)&&/\bSafari\b/.test(J[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(y)&&J[1])&&(a=J[J.length-1])&&f.push(a);f.length&&(f=["("+f.join("; ")+")"]);X&&K&&0>K.indexOf(X)&&f.push("on "+X);K&&f.push((/^on /.test(f[f.length-
1])?"":"on ")+K);if(B){var da=(a=/ ([\d.+]+)$/.exec(B))&&"/"==B.charAt(B.length-a[0].length-1);B={architecture:32,family:a&&!da?B.replace(a[0],""):B,version:a?a[1]:null,toString:function(){var S=this.version;return this.family+(S&&!da?" "+S:"")+(64==this.architecture?" 64-bit":"")}}}(a=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(I))&&!/\bi686\b/i.test(I)?(B&&(B.architecture=64,B.family=B.family.replace(RegExp(" *"+a),"")),y&&(/\bWOW64\b/i.test(h)||R&&/\w(?:86|32)$/.test(z.cpuClass||z.platform)&&!/\bWin64; x64\b/i.test(h))&&
f.unshift("32-bit")):B&&/^OS X/.test(B.family)&&"Chrome"==y&&39<=parseFloat(n)&&(B.architecture=64);h||(h=null);x={};x.description=h;x.layout=J&&J[0];x.manufacturer=X;x.name=y;x.prerelease=Y;x.product=K;x.ua=h;x.version=y&&n;x.os=B||{architecture:null,family:null,version:null,toString:function(){return"null"}};x.parse=k;x.toString=function(){return this.description||""};x.version&&f.unshift(n);x.name&&f.unshift(y);B&&y&&(B!=String(B).split(" ")[0]||B!=y.split(" ")[0]&&!K)&&f.push(K?"("+B+")":"on "+
B);f.length&&(x.description=f.join(" "));return x}var c={"function":!0,object:!0},u=c[typeof window]&&window||this,t=c[typeof exports]&&exports;c=c[typeof module]&&module&&!module.nodeType&&module;var D=t&&c&&"object"==typeof global&&global;!D||D.global!==D&&D.window!==D&&D.self!==D||(u=D);var C=Math.pow(2,53)-1,F=/\bOpera/;D=Object.prototype;var E=D.hasOwnProperty,v=D.toString,A=k();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(u.platform=A,define(function(){return A})):t&&
c?m(A,function(h,H){t[H]=h}):u.platform=A}).call(this);var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX=0,s_iOffsetY=0,s_bFocus=!0;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){if(isIpad())return!0;for(var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");b.length;)if(navigator.platform===b.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function isIpad(){var b=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!b&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:b}function isMobile(){return isIpad()?!0:navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?!0:!1}
function getSize(b){var g=b.toLowerCase(),d=window.document,m=d.documentElement;if(void 0===window["inner"+b])b=m["client"+b];else if(window["inner"+b]!=m["client"+b]){var l=d.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var q=d.createElement("div");q.id="vpw-test-d";q.style.cssText="position:absolute;top:-1000px";q.innerHTML="<style>@media("+g+":"+m["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";l.appendChild(q);m.insertBefore(l,d.head);
b=7==q["offset"+b]?m["client"+b]:window["inner"+b];m.removeChild(l)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var g=getSize("Width");s_bFocus&&_checkOrientation(g,b);var d=Math.min(b/CANVAS_HEIGHT,g/CANVAS_WIDTH),m=Math.round(CANVAS_WIDTH*d);d=Math.round(CANVAS_HEIGHT*d);if(d<b){var l=b-d;d+=l;m+=CANVAS_WIDTH/CANVAS_HEIGHT*l}else m<g&&(l=g-m,m+=l,d+=CANVAS_HEIGHT/CANVAS_WIDTH*l);l=b/2-d/2;var q=g/2-m/2,e=CANVAS_WIDTH/m;if(q*e<-EDGEBOARD_X||
l*e<-EDGEBOARD_Y)d=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*EDGEBOARD_X)),m=Math.round(CANVAS_WIDTH*d),d=Math.round(CANVAS_HEIGHT*d),l=(b-d)/2,q=(g-m)/2,e=CANVAS_WIDTH/m;s_iOffsetX=-1*q*e;s_iOffsetY=-1*l*e;0<=l&&(s_iOffsetY=0);0<=q&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLanguageMenu&&s_oLanguageMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone&&s_oStage?
(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*m,s_oStage.canvas.height=2*d,canvas.style.width=m+"px",canvas.style.height=d+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(m/CANVAS_WIDTH,d/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",m+"px"),$("#canvas").css("height",d+"px")):s_oStage&&(s_oStage.canvas.width=m,s_oStage.canvas.height=d,s_iScaleFactor=Math.min(m/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>l||(l=(b-d)/2);$("#canvas").css("top",
l+"px");$("#canvas").css("left",q+"px");fullscreenHandler()}}
function _checkOrientation(b,g){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>g?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(b,g,d){var m=new createjs.Bitmap(b),l=new createjs.Shape;g&&d?l.graphics.beginFill("#fff").drawRect(0,0,g,d):l.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);m.hitArea=l;return m}function createSprite(b,g,d,m,l,q){b=null!==g?new createjs.Sprite(b,g):new createjs.Sprite(b);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-d,-m,l,q);b.hitArea=g;return b}
function randomFloatBetween(b,g,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(b+Math.random()*(g-b),g).toFixed(d))}function formatTime(b){b/=1E3;var g=Math.floor(b/60);b=Math.floor(b-60*g);var d="";d=10>g?d+("0"+g+":"):d+(g+":");return 10>b?d+("0"+b):d+b}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var g=b.length,d,m;0<g;)m=Math.floor(Math.random()*g),g--,d=b[g],b[g]=b[m],b[m]=d;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);b.dispatchEvent(g)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var g=window.location.search.substring(1).split("&"),d=0;d<g.length;d++){var m=g[d].split("=");if(m[0]==b)return m[1]}}
(function(){function b(d){var m={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};d=d||window.event;d.type in m?document.body.className=m[d.type]:(document.body.className=this[g]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var g="hidden";g in document?document.addEventListener("visibilitychange",b):(g="mozHidden")in document?document.addEventListener("mozvisibilitychange",
b):(g="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",b):(g="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oLanguageMenu&&s_oLanguageMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oLanguageMenu&&s_oLanguageMenu.resetFullscreenBut()});
function playSound(b,g,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[b].play(),s_aSounds[b].volume(g),s_aSounds[b].loop(d),s_aSounds[b]):null}function stopSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].stop()}function setVolume(b,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].volume(g)}function setMute(b,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].mute(g)}
function CSpriteLibrary(){var b={},g,d,m,l,q,e;this.init=function(r,k,c){g={};m=d=0;l=r;q=k;e=c};this.addSprite=function(r,k){if(!b.hasOwnProperty(r)){var c=new Image;b[r]=g[r]={szPath:k,oSprite:c,bLoaded:!1};d++}};this.getSprite=function(r){return b.hasOwnProperty(r)?b[r].oSprite:null};this._onSpritesLoaded=function(){d=0;q.call(e)};this._onSpriteLoaded=function(){l.call(e);++m===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var r in g)g[r].oSprite.oSpriteLibrary=this,g[r].oSprite.szKey=
r,g[r].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},g[r].oSprite.onerror=function(k){var c=k.currentTarget;setTimeout(function(){g[c.szKey].oSprite.src=g[c.szKey].szPath},500)},g[r].oSprite.src=g[r].szPath};this.setLoaded=function(r){b[r].bLoaded=!0};this.isLoaded=function(r){return b[r].bLoaded};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=1920,EDGEBOARD_X=120,EDGEBOARD_Y=150,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="ArialRoundedMTBold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_LANGUAGE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,LANGUAGE_EN=0,LANGUAGE_FR=1,LANGUAGE_IT=2,LANGUAGE_ES=3,LANGUAGE_GER=4,LANGUAGE_POR=5,PADDING=10,GAME_ELEMENT_HEIGHT=-180,GAME_LANGUAGE,NUMBER_OF_WORDS=21,NUMBER_QUEST_IMAGE=4,BONUS_TIME=!0,ALPHABET=
[];ALPHABET=["AAABCDEEEFGHHIIJKLMNNOOOPQRSSTTTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"AAABCDEEEFGHIIIJKLLMNNOOPQRSTTUVWLXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("")];var SHOW_CREDITS=!0,SOUNDTRACK_VOLUME_IN_GAME=1,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
function CPreloader(){var b,g,d,m,l,q,e,r,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(c);c=s_oSpriteLibrary.getSprite("200x200");e=createBitmap(c);e.regX=.5*c.width;e.regY=.5*c.height;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-180;k.addChild(e);r=new createjs.Shape;r.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(e.x-100,e.y-100,200,200,10);k.addChild(r);e.mask=r;c=s_oSpriteLibrary.getSprite("progress_bar");m=createBitmap(c);m.x=CANVAS_WIDTH/2-
c.width/2;m.y=CANVAS_HEIGHT/2+50;k.addChild(m);b=c.width;g=c.height;l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(m.x,m.y,1,g);k.addChild(l);m.mask=l;d=new createjs.Text("","40px "+PRIMARY_FONT,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+110;d.textBaseline="alphabetic";d.textAlign="center";k.addChild(d);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(q);createjs.Tween.get(q).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(q);
k.removeChild(q)})};this.refreshLoader=function(c){d.text=c+"%";100===c&&(s_oMain._onRemovePreloader(),d.visible=!1,m.visible=!1);l.graphics.clear();c=Math.floor(c*b/100);l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(m.x,m.y,c,g)};this._init()}
function CMain(b){var g,d=0,m=0,l=STATE_LOADING,q,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_bMobile=isMobile();!1===s_bMobile?s_oStage.enableMouseOver(20):createjs.Touch.enable(s_oStage,!0);s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=30;navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;seekAndDestroy()?
q=new CPreloader:window.location.href="https://www.codethislab.com/contact-us.html"};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();g=!0};this.soundLoaded=function(){d++;q.refreshLoader(Math.floor(d/m*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,
volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"guessed",loop:!1,volume:1,ingamename:"guessed"});s_aSoundsInfo.push({path:"./sounds/",filename:"wrong",loop:!1,volume:1,ingamename:"wrong"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});m+=s_aSoundsInfo.length;s_aSounds=[];for(var k=0;k<s_aSoundsInfo.length;k++)this.tryToLoadSound(s_aSoundsInfo[k],!1)};this.tryToLoadSound=function(k,c){setTimeout(function(){s_aSounds[k.ingamename]=
new Howl({src:[k.path+k.filename+".mp3"],autoplay:!1,preload:!0,loop:k.loop,volume:k.volume,onload:s_oMain.soundLoaded,onloaderror:function(u,t){for(var D=0;D<s_aSoundsInfo.length;D++)if(u===s_aSounds[s_aSoundsInfo[D].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[D],!0);break}},onplayerror:function(u){for(var t=0;t<s_aSoundsInfo.length;t++)if(u===s_aSounds[s_aSoundsInfo[t].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[t].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[t].ingamename].play();
"soundtrack"===s_aSoundsInfo[t].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},c?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_gameover","./sprites/bg_gameover.png");s_oSpriteLibrary.addSprite("load_level",
"./sprites/load_level.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("curtain_dx","./sprites/curtain_dx.jpg");s_oSpriteLibrary.addSprite("curtain_sx","./sprites/curtain_sx.jpg");s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("logo_small","./sprites/logo_small.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("letterbox",
"./sprites/letterbox.png");s_oSpriteLibrary.addSprite("letter","./sprites/letter.png");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("level_panel","./sprites/level_panel.png");s_oSpriteLibrary.addSprite("success","./sprites/success.png");s_oSpriteLibrary.addSprite("mistake","./sprites/mistake.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("text_copyright","./sprites/text_copyright.png");s_oSpriteLibrary.addSprite("but_flag_it",
"./sprites/but_flag_it.png");s_oSpriteLibrary.addSprite("but_flag_en","./sprites/but_flag_en.png");s_oSpriteLibrary.addSprite("but_flag_fr","./sprites/but_flag_fr.png");s_oSpriteLibrary.addSprite("but_flag_es","./sprites/but_flag_es.png");s_oSpriteLibrary.addSprite("but_flag_ger","./sprites/but_flag_ger.png");s_oSpriteLibrary.addSprite("but_flag_por","./sprites/but_flag_por.png");s_oSpriteLibrary.addSprite("but_add_a_letter","./sprites/but_add_a_letter.png");s_oSpriteLibrary.addSprite("but_remove_letters",
"./sprites/but_remove_letters.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("imghome1","./sprites/imghome1.png");s_oSpriteLibrary.addSprite("imghome2","./sprites/imghome2.jpg");s_oSpriteLibrary.addSprite("imghome3","./sprites/imghome3.jpg");s_oSpriteLibrary.addSprite("imghome4","./sprites/imghome4.jpg");s_oSpriteLibrary.addSprite("imgcat1","./sprites/imgcat1.jpg");s_oSpriteLibrary.addSprite("imgcat2",
"./sprites/imgcat2.jpg");s_oSpriteLibrary.addSprite("imgcat3","./sprites/imgcat3.jpg");s_oSpriteLibrary.addSprite("imgcat4","./sprites/imgcat4.jpg");s_oSpriteLibrary.addSprite("imghappy1","./sprites/imghappy1.jpg");s_oSpriteLibrary.addSprite("imghappy2","./sprites/imghappy2.jpg");s_oSpriteLibrary.addSprite("imghappy3","./sprites/imghappy3.jpg");s_oSpriteLibrary.addSprite("imghappy4","./sprites/imghappy4.jpg");s_oSpriteLibrary.addSprite("imgdrink1","./sprites/imgdrink1.jpg");s_oSpriteLibrary.addSprite("imgdrink2",
"./sprites/imgdrink2.jpg");s_oSpriteLibrary.addSprite("imgdrink3","./sprites/imgdrink3.jpg");s_oSpriteLibrary.addSprite("imgdrink4","./sprites/imgdrink4.jpg");s_oSpriteLibrary.addSprite("imgminute1","./sprites/imgminute1.jpg");s_oSpriteLibrary.addSprite("imgminute2","./sprites/imgminute2.jpg");s_oSpriteLibrary.addSprite("imgminute3","./sprites/imgminute3.jpg");s_oSpriteLibrary.addSprite("imgminute4","./sprites/imgminute4.jpg");s_oSpriteLibrary.addSprite("imgsound1","./sprites/imgsound1.jpg");s_oSpriteLibrary.addSprite("imgsound2",
"./sprites/imgsound2.jpg");s_oSpriteLibrary.addSprite("imgsound3","./sprites/imgsound3.jpg");s_oSpriteLibrary.addSprite("imgsound4","./sprites/imgsound4.jpg");s_oSpriteLibrary.addSprite("imgcacao1","./sprites/imgcacao1.jpg");s_oSpriteLibrary.addSprite("imgcacao2","./sprites/imgcacao2.jpg");s_oSpriteLibrary.addSprite("imgcacao3","./sprites/imgcacao3.jpg");s_oSpriteLibrary.addSprite("imgcacao4","./sprites/imgcacao4.jpg");s_oSpriteLibrary.addSprite("imgfull1","./sprites/imgfull1.jpg");s_oSpriteLibrary.addSprite("imgfull2",
"./sprites/imgfull2.jpg");s_oSpriteLibrary.addSprite("imgfull3","./sprites/imgfull3.jpg");s_oSpriteLibrary.addSprite("imgfull4","./sprites/imgfull4.jpg");s_oSpriteLibrary.addSprite("imgcold1","./sprites/imgcold1.jpg");s_oSpriteLibrary.addSprite("imgcold2","./sprites/imgcold2.jpg");s_oSpriteLibrary.addSprite("imgcold3","./sprites/imgcold3.jpg");s_oSpriteLibrary.addSprite("imgcold4","./sprites/imgcold4.jpg");s_oSpriteLibrary.addSprite("imgviolet1","./sprites/imgviolet1.jpg");s_oSpriteLibrary.addSprite("imgviolet2",
"./sprites/imgviolet2.jpg");s_oSpriteLibrary.addSprite("imgviolet3","./sprites/imgviolet3.jpg");s_oSpriteLibrary.addSprite("imgviolet4","./sprites/imgviolet4.jpg");s_oSpriteLibrary.addSprite("imgchord1","./sprites/imgchord1.jpg");s_oSpriteLibrary.addSprite("imgchord2","./sprites/imgchord2.jpg");s_oSpriteLibrary.addSprite("imgchord3","./sprites/imgchord3.jpg");s_oSpriteLibrary.addSprite("imgchord4","./sprites/imgchord4.jpg");s_oSpriteLibrary.addSprite("imgcolors1","./sprites/imgcolors1.jpg");s_oSpriteLibrary.addSprite("imgcolors2",
"./sprites/imgcolors2.jpg");s_oSpriteLibrary.addSprite("imgcolors3","./sprites/imgcolors3.jpg");s_oSpriteLibrary.addSprite("imgcolors4","./sprites/imgcolors4.jpg");s_oSpriteLibrary.addSprite("imgrubber1","./sprites/imgrubber1.jpg");s_oSpriteLibrary.addSprite("imgrubber2","./sprites/imgrubber2.jpg");s_oSpriteLibrary.addSprite("imgrubber3","./sprites/imgrubber3.jpg");s_oSpriteLibrary.addSprite("imgrubber4","./sprites/imgrubber4.jpg");s_oSpriteLibrary.addSprite("imgdelete1","./sprites/imgdelete1.jpg");
s_oSpriteLibrary.addSprite("imgdelete2","./sprites/imgdelete2.jpg");s_oSpriteLibrary.addSprite("imgdelete3","./sprites/imgdelete3.jpg");s_oSpriteLibrary.addSprite("imgdelete4","./sprites/imgdelete4.jpg");s_oSpriteLibrary.addSprite("imgclimb1","./sprites/imgclimb1.jpg");s_oSpriteLibrary.addSprite("imgclimb2","./sprites/imgclimb2.jpg");s_oSpriteLibrary.addSprite("imgclimb3","./sprites/imgclimb3.jpg");s_oSpriteLibrary.addSprite("imgclimb4","./sprites/imgclimb4.jpg");s_oSpriteLibrary.addSprite("imgorange1",
"./sprites/imgorange1.jpg");s_oSpriteLibrary.addSprite("imgorange2","./sprites/imgorange2.jpg");s_oSpriteLibrary.addSprite("imgorange3","./sprites/imgorange3.jpg");s_oSpriteLibrary.addSprite("imgorange4","./sprites/imgorange4.jpg");s_oSpriteLibrary.addSprite("imgbed1","./sprites/imgbed1.jpg");s_oSpriteLibrary.addSprite("imgbed2","./sprites/imgbed2.jpg");s_oSpriteLibrary.addSprite("imgbed3","./sprites/imgbed3.jpg");s_oSpriteLibrary.addSprite("imgbed4","./sprites/imgbed4.jpg");s_oSpriteLibrary.addSprite("imgisland1",
"./sprites/imgisland1.jpg");s_oSpriteLibrary.addSprite("imgisland2","./sprites/imgisland2.jpg");s_oSpriteLibrary.addSprite("imgisland3","./sprites/imgisland3.jpg");s_oSpriteLibrary.addSprite("imgisland4","./sprites/imgisland4.jpg");s_oSpriteLibrary.addSprite("imgwine1","./sprites/imgwine1.jpg");s_oSpriteLibrary.addSprite("imgwine2","./sprites/imgwine2.jpg");s_oSpriteLibrary.addSprite("imgwine3","./sprites/imgwine3.jpg");s_oSpriteLibrary.addSprite("imgwine4","./sprites/imgwine4.jpg");s_oSpriteLibrary.addSprite("imground1",
"./sprites/imground1.jpg");s_oSpriteLibrary.addSprite("imground2","./sprites/imground2.jpg");s_oSpriteLibrary.addSprite("imground3","./sprites/imground3.jpg");s_oSpriteLibrary.addSprite("imground4","./sprites/imground4.jpg");s_oSpriteLibrary.addSprite("imgiron1","./sprites/imgiron1.jpg");s_oSpriteLibrary.addSprite("imgiron2","./sprites/imgiron2.jpg");s_oSpriteLibrary.addSprite("imgiron3","./sprites/imgiron3.jpg");s_oSpriteLibrary.addSprite("imgiron4","./sprites/imgiron4.jpg");s_oSpriteLibrary.addSprite("but_menu",
"./sprites/but_menu.png");s_oSpriteLibrary.addSprite("shadow","./sprites/shadow_of_images.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");m+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;q.refreshLoader(Math.floor(d/m*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){q.unload();s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;l=STATE_MENU};
this.gotoGame=function(k){e=new CGame(k,r);l=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoGameOver=function(k){new CGameOver(k)};this.gotoLanguage=function(){new CLanguageMenu};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(k){if(!1!==g){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);l===STATE_GAME&&e.update();s_oStage.update(k)}};s_oMain=this;var r=b;ENABLE_CHECK_ORIENTATION=b.check_orientation;ENABLE_FULLSCREEN=b.fullscreen;GAME_LANGUAGE=b.game_language;s_bAudioActive=b.audio_enable_on_startup;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_iLanguageSelected,s_aSounds,s_bFullscreen=!1,s_aSoundsInfo;
function CTextButton(b,g,d,m,l,q,e,r,k){var c,u,t,D,C,F,E,v,A,h,H,p,x,f,z,n={};this._init=function(w,M,G,O,P,U,T){c=!1;u=1;z=!1;v=[];A=[];var W=createBitmap(G),Q=Math.ceil(T/20);f=new createjs.Text(O,"bold "+T+"px "+P,"#000000");f.textAlign="center";f.textBaseline="alphabetic";var Z=f.getBounds();f.x=G.width/2+Q;f.y=Math.floor(G.height/2+Z.height/3+Q)+r;f.alpha=.5;x=new createjs.Text(O,"bold "+T+"px "+P,U);x.textAlign="center";x.textBaseline="alphabetic";Z=x.getBounds();x.x=G.width/2;x.y=Math.floor(G.height/
2+Z.height/3)+r;p=new createjs.Container;p.x=w;p.y=M;p.regX=G.width/2;p.regY=G.height/2;p.addChild(W,f,x);k.addChild(p);p.cursor="pointer";this._initListener()};this.setExtraData=function(w,M){n[w]=M};this.getExtraData=function(w){return n[w]};this.unload=function(){p.off("mousedown",h);p.off("pressup",H);k.removeChild(p)};this.setUsed=function(w){z=w};this.getUsed=function(){return z};this.getID=function(){return E};this.setCursorType=function(w){p.cursor=w};this.setTextCenterX=function(w){x+=w;
x+=w};this.changeChildIndex=function(w){s_oStage.setChildIndex(p,w)};this.setVisible=function(w){p.visible=w};this.getVisible=function(){return p.visible};this._initListener=function(){h=p.on("mousedown",this.buttonDown);H=p.on("pressup",this.buttonRelease)};this.addEventListener=function(w,M,G){v[w]=M;A[w]=G};this.addEventListenerWithParams=function(w,M,G,O,P,U,T,W){v[w]=M;A[w]=G;t=O;D=T;C=P;F=U;E=W};this.buttonRelease=function(){c||(p.scaleX=1*u,p.scaleY=1*u,playSound("click",1,!1),v[ON_MOUSE_UP]&&
v[ON_MOUSE_UP].call(A[ON_MOUSE_UP],t,C,F,D,E))};this.buttonDown=function(){c||(p.scaleX=.9*u,p.scaleY=.9*u,v[ON_MOUSE_DOWN]&&v[ON_MOUSE_DOWN].call(A[ON_MOUSE_DOWN],t,C,F,D,E))};this.setTextPosition=function(w){x.y=w;f.y=w+2};this.getText=function(){return x.text};this.setText=function(w){x.text=w;f.text=w};this.setPosition=function(w,M){p.x=w;p.y=M};this.setX=function(w){p.x=w};this.setY=function(w){p.y=w};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};
this.block=function(w){c=w};this.setScale=function(w){u=w;p.scaleX=w;p.scaleY=w};this._init(b,g,d,m,l,q,e);return this}
function CToggle(b,g,d,m,l){var q,e,r,k;this._init=function(c,u,t,D){e=[];r=[];var C=new createjs.SpriteSheet({images:[t],frames:{width:t.width/2,height:t.height,regX:t.width/2/2,regY:t.height/2},animations:{state_true:[0],state_false:[1]}});q=D;k=createSprite(C,"state_"+q,t.width/2/2,t.height/2,t.width/2,t.height);k.stop();k.x=c;k.y=u;k.cursor="pointer";b.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);b.removeChild(k)};
this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(c,u,t){e[c]=u;r[c]=t};this.setActive=function(c){q=c;k.gotoAndStop("state_"+q)};this.setCursorType=function(c){k.cursor=c};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,!1);q=!q;k.gotoAndStop("state_"+q);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(r[ON_MOUSE_UP],q)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN])};
this.setPosition=function(c,u){k.x=c;k.y=u};this._init(g,d,m,l)}
function CGfxButton(b,g,d,m){var l,q,e,r,k,c,u,t,D,C,F,E;this._init=function(v,A,h){l=!1;E=1;q=[];e=[];c=createBitmap(h);c.x=v;c.y=A;c.regX=h.width/2;c.regY=h.height/2;b.addChild(c);c.cursor="pointer";this._initListener()};this.changeChildIndex=function(v){b.setChildIndex(c,v)};this.unload=function(){c.off("mousedown",r);c.off("pressup",k);b.removeChild(c)};this.setVisible=function(v){c.visible=v};this.getVisible=function(){return c.visible};this._initListener=function(){r=c.on("mousedown",this.buttonDown);
k=c.on("pressup",this.buttonRelease)};this.setCursorType=function(v){c.cursor=v};this.setAlpha=function(v){c.alpha=v};this.addEventListener=function(v,A,h){q[v]=A;e[v]=h};this.addEventListenerWithParams=function(v,A,h,H,p,x,f,z){q[v]=A;e[v]=h;u=H;t=f;D=p;C=x;F=z};this.buttonRelease=function(){l||(c.scaleX=1*E,c.scaleY=1*E,playSound("click",1,!1),q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(e[ON_MOUSE_UP],u,D,C,t,F))};this.buttonDown=function(){l||(c.scaleX=.95*E,c.scaleY=.95*E,q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],
u,D,C,t,F))};this.getScale=function(){return E};this.setPosition=function(v,A){c.x=v;c.y=A};this.setX=function(v){c.x=v};this.setY=function(v){c.y=v};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this.block=function(v){l=v};this.setScale=function(v){E=v;c.scaleX=v;c.scaleY=v};this._init(g,d,m);return this}
function CMenu(){var b,g,d,m,l,q,e,r,k,c,u,t=null,D,C=null,F=null;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var E=s_oSpriteLibrary.getSprite("but_play");r=new CGfxButton(s_oStage,CANVAS_WIDTH/2,CANVAS_HEIGHT/2+560,E);r.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);E=s_oSpriteLibrary.getSprite("audio_icon");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(l=CANVAS_WIDTH-E.height/2-PADDING,q=E.height/2+PADDING,c=new CToggle(s_oStage,l,q,E,
s_bAudioActive),c.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=l-E.width/2-10,g=q):(b=CANVAS_WIDTH-E.height/2-PADDING,g=E.height/2+PADDING);SHOW_CREDITS&&(u=new CGfxButton(s_oStage,b,g,s_oSpriteLibrary.getSprite("but_credits"),!0),u.addEventListener(ON_MOUSE_UP,this._onCredits,this));!1===s_bMobile&&(c.setCursorType("pointer"),r.setCursorType("pointer"));E=window.document;var v=E.documentElement;C=v.requestFullscreen||v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;
F=E.exitFullscreen||E.mozCancelFullScreen||E.webkitExitFullscreen||E.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(C=!1);C&&screenfull.isEnabled&&(E=s_oSpriteLibrary.getSprite("but_fullscreen"),d=E.width/4+10,m=g,D=new CToggle(s_oStage,d,m,E,s_bFullscreen,s_oStage),D.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:0},1E3).call(function(){s_oStage.removeChild(k);
k=null});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){r.unload();r=null;SHOW_CREDITS&&u.unload();s_oStage.removeChild(e);e=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c.unload(),c=null;C&&screenfull.isEnabled&&D.unload();s_oMenu=null};this.exitFromCredits=function(){t=null};this.refreshButtonPos=function(E,v){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.setPosition(l-E,v+q);SHOW_CREDITS&&u.setPosition(b-E,v+g);null!==t&&t.refreshButtonPos(E,v);C&&screenfull.isEnabled&&
D.setPosition(d+E,m+v)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){t=new CCreditsPanel};this._onButPlayRelease=function(){this.unload();0>GAME_LANGUAGE?s_oMain.gotoLanguage():s_oMain.gotoGame(GAME_LANGUAGE)};this.resetFullscreenBut=function(){C&&screenfull.isEnabled&&D.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?F.call(window.document):C.call(window.document.documentElement);sizeHandler()};
s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b,g){var d,m,l,q,e,r,k,c,u;this._init=function(){var t=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(t);N_MAX_WORDS_TO_GUESS>NUMBER_OF_WORDS&&(N_MAX_WORDS_TO_GUESS=NUMBER_OF_WORDS);l=0;e=START_MONEY;u=0;m=new CGameSettings(b,l);m.loadQuest();m.showPicture();m.placeLetters();m.shuffleLetters();d=new CInterface(e);d.refreshNuMLevel(l);d.refreshMoney(e);$(s_oMain).trigger("start_level",{ilevel:l});q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,
CANVAS_WIDTH,CANVAS_HEIGHT);t=s_oSpriteLibrary.getSprite("curtain_dx");k=createBitmap(t);k.x=CANVAS_WIDTH;k.visible=!1;s_oStage.addChild(k);t=s_oSpriteLibrary.getSprite("curtain_sx");c=createBitmap(t);c.x=0;c.regX=t.width;c.visible=!1;s_oStage.addChild(c);c.addEventListener("click",function(){});k.addEventListener("click",function(){});s_oStage.addChild(q);createjs.Tween.get(q).to({alpha:0},1E3).call(function(){q.visible=!1})};this.wordGuessed=function(){l++;l<N_MAX_WORDS_TO_GUESS?(s_oStage.setChildIndex(k,
s_oStage.numChildren-1),s_oStage.setChildIndex(c,s_oStage.numChildren-1),k.visible=!0,c.visible=!0,createjs.Tween.get(c,{override:!0}).to({x:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut),createjs.Tween.get(k,{override:!0}).to({x:CANVAS_WIDTH/2},700,createjs.Ease.cubicOut).call(function(){s_oGame.goToNextLevel(l,e)})):($(s_oMain).trigger("share_event",e),this.unload(),s_oMain.gotoGameOver(e))};this.goToNextLevel=function(t,D){m.setLevel(t);m.unloadQuest(l-1);m.loadQuest();m.showPicture();m.placeLetters();
m.shuffleLetters();d.refreshNuMLevel(t);d.refreshMoney(D);d.resetCounter();s_oStage.setChildIndex(k,s_oStage.numChildren-1);s_oStage.setChildIndex(c,s_oStage.numChildren-1);var C=s_oSpriteLibrary.getSprite("logo"),F=createBitmap(C);F.x=CANVAS_WIDTH/2;F.y=0;F.regX=C.width/2;F.regY=C.height/2;s_oStage.addChild(F);createjs.Tween.get(F,{override:!0}).to({y:CANVAS_HEIGHT/2},1300,createjs.Ease.elasticOut).call(function(){u++;u===NUM_QUIZ_FOR_ADS&&(u=0,$(s_oMain).trigger("show_interlevel_ad"));createjs.Tween.get(c,
{override:!0}).wait(200).to({x:0},700,createjs.Ease.cubicOut);createjs.Tween.get(k,{override:!0}).wait(200).to({x:CANVAS_WIDTH},700,createjs.Ease.cubicOut).call(function(){c.visible=!1;k.visible=!1;$(s_oMain).trigger("start_level",{ilevel:t});!0===BONUS_TIME&&s_oGame.stoppedTime(!1)});createjs.Tween.get(F,{override:!0}).wait(100).to({y:-C.height},700,createjs.Ease.backIn).call(function(){s_oStage.removeChild(F);F=null})})};this.animEarnedMoney=function(t){r=t+d.getCount();e+=r;d.addedMoneyAnim(r,
2E3,"#00ff00");d.refreshMoney(e)};this.animSpentMoney=function(t){this.manageMoney(t);d.addedMoneyAnim(t,2E3,"#ff0000")};this.manageMoney=function(t){e+=t;d.refreshMoney(e)};this.getMoney=function(){return e};this.restartGame=function(){this.unload();this._init()};this.stoppedTime=function(t){d.setStoppedTime(t)};this.unload=function(){d.unload();m.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");
$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("restart")};this.update=function(){!0===BONUS_TIME&&d.update()};s_oGame=this;N_MAX_WORDS_TO_GUESS=g.words_to_guess;NUM_OF_SPAWN_LETTER=g.spawn_letters;START_MONEY=g.start_money;COST_OF_A_LETTER=g.cost_of_a_letter;COST_FOR_REMOVE_LETTERS=g.cost_for_remove_letters;TIME_FOR_EVERY_WORD=g.time_for_every_quest;NUM_QUIZ_FOR_ADS=g.num_quiz_before_ads;this._init()}var s_oGame;
function CGameSettings(b,g){var d,m,l=[],q=[],e,r,k,c,u,t,D,C,F,E,v,A,h,H,p,x;this._init=function(){d=b;A=g;t=0;r=[];k=[];c=[];h=[];p=[];H=0;x=!0;4<NUMBER_QUEST_IMAGE&&(NUMBER_QUEST_IMAGE=4);for(e=0;e<N_MAX_WORDS_TO_GUESS;e++)l[e]=Array(NUMBER_QUEST_IMAGE),q[e]=Array(NUMBER_QUEST_IMAGE);for(var f=0;f<NUMBER_OF_WORDS;f++)p[f]=f;p=shuffle(p);f=s_oSpriteLibrary.getSprite("success");F=createBitmap(f);F.x=CANVAS_WIDTH/2;F.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;F.regX=f.width/2;F.regY=f.height/2;F.visible=
!1;s_oStage.addChild(F);f=s_oSpriteLibrary.getSprite("mistake");C=createBitmap(f);C.x=CANVAS_WIDTH/2;C.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;C.regX=f.width/2;C.regY=f.height/2;C.visible=!1;s_oStage.addChild(C);f=s_oSpriteLibrary.getSprite("but_next");D=new CGfxButton(s_oStage,CANVAS_WIDTH/2+430,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+700,f);D.addEventListener(ON_MOUSE_UP,this._onNextLevel,this);D.setVisible(!1);D.setCursorType("pointer");f=s_oSpriteLibrary.getSprite("but_remove_letters");E=new CGfxButton(s_oStage,
CANVAS_WIDTH/2-100,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+910,f);E.addEventListener(ON_MOUSE_UP,this.removeSomeLetters,this);E.setCursorType("pointer");f=s_oSpriteLibrary.getSprite("but_add_a_letter");v=new CGfxButton(s_oStage,CANVAS_WIDTH/2+100,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+910,f);v.addEventListener(ON_MOUSE_UP,this.addALetter,this);v.setCursorType("pointer")};this.loadQuest=function(){m=s_aQuestions[p[A]].answer[d];for(var f=0;f<NUMBER_QUEST_IMAGE;f++){var z=s_oSpriteLibrary.getSprite(s_aQuestions[p[A]].img[0].file[f]);
l[A][f]=new CGfxButton(s_oStage,CANVAS_WIDTH/2,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT,z);z=s_oSpriteLibrary.getSprite("text_copyright");q[A][f]=new CText(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+320,z,s_aQuestions[p[A]].img[0].copyright[f],PRIMARY_FONT,"#ffffff",25,0);q[A][f].setVisible(!1)}};this.unloadQuest=function(f){for(var z=0;4>z;z++)l[f][z].unload(),l[f][z]=null,q[f][z].unload(),q[f][z]=null;for(e=0;e<u;e++)r[e].unload(),r[e]=null;for(e=0;e<NUM_OF_SPAWN_LETTER;e++)c[e].unload(),
c[e]=null};this.unload=function(){v.unload();v=null;s_oStage.removeChild(C);C=null;s_oStage.removeChild(F);F=null;E.unload();E=null;this.unloadQuest(A);s_oGameSettings=null};this.removeSomeLetters=function(){if(!(s_oGame.getMoney()<COST_FOR_REMOVE_LETTERS-1)){for(var f=[],z=0;z<NUM_OF_SPAWN_LETTER;z++)c[z].getVisible()&&f.push(c[z]);var n=3,w=!1;for(z=0;z<f.length;z++){for(var M=!0,G=0;G<u;G++)if(f[z].getText()===m.charAt(G)){M=!1;break}if(!0===M&&(f[z].setVisible(!1),k[f[z].getExtraData("boxposition")]=
!1,f[z].setExtraData("boxposition",null),n--,w=!0,0===n))break}!0===w&&s_oGame.animSpentMoney(-COST_FOR_REMOVE_LETTERS)}};this.addALetter=function(){var f=!0,z=0;if(!(s_oGame.getMoney()<COST_OF_A_LETTER-1)&&H<u&&s_oGame.getMoney()>COST_OF_A_LETTER-1)for(;!0===f;){var n=Math.floor(Math.random()*u);if(!0===k[n])z===u&&(f=!1),z++;else for(e=0;e<NUM_OF_SPAWN_LETTER;e++)if(c[e].getText()===m.charAt(n)&&!1===c[e].getUsed()){c[e].setPosition(r[n].getX(),r[n].getY());c[e].block(!0);c[e].setUsed(!0);h[n]=
m.charAt(n);c[e].setExtraData("boxposition",n);k[c[e].getExtraData("boxposition")]=!0;s_oGame.animSpentMoney(-COST_OF_A_LETTER);f=!1;H++;this.checkVictory();break}}};this._onNextLevel=function(){createjs.Tween.get(F).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){F.visible=!1});D.setVisible(!1);H=t=0;s_oGame.wordGuessed()};this.placeLetters=function(){for(var f=s_oSpriteLibrary.getSprite("letter"),z=f.width,n=CANVAS_WIDTH/2-Math.round(NUM_OF_SPAWN_LETTER/2)*z/2+f.width/2-z,w,M,G=0;G<u;G++)0!=
G%2?w=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+750:(w=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+630,n+=z),c[G]=new CTextButton(n,w,f,m.charAt(G),PRIMARY_FONT,"#382074",66,-10,s_oStage),c[G].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,m.charAt(G),G),!1===s_bMobile&&c[G].setCursorType("pointer");for(G=u;G<NUM_OF_SPAWN_LETTER;G++)M=Math.floor(Math.random()*ALPHABET[d].length),0!=G%2?w=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+750:(w=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+630,n+=z),c[G]=new CTextButton(n,
w,f,ALPHABET[d][M],PRIMARY_FONT,"#382074",66,-10,s_oStage),c[G].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,ALPHABET[d][M],G),!1===s_bMobile&&c[G].setCursorType("pointer");v.block(!1);E.block(!1)};this.returnPosition=function(f,z,n,w,M){c[n].setPosition(f,z);c[n].addEventListenerWithParams(ON_MOUSE_UP,this._onChooseWord,this,w,n);c[n].setUsed(!1);h[M]=null;x=!0;!0===C.visible&&createjs.Tween.get(C).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){C.visible=!1});k[M]=!1;
e=0;for(f=!1;e<u&&!1===f;)!1===k[e]&&(t=e,f=!0),e++};this.shuffleLetters=function(){for(e=0;e<NUM_OF_SPAWN_LETTER;e++){var f=Math.floor(Math.random()*NUM_OF_SPAWN_LETTER),z=c[e].getX(),n=c[e].getY();c[e].setPosition(c[f].getX(),c[f].getY());c[f].setPosition(z,n)}};this._onChooseWord=function(f,z){if(t<u){for(var n=0,w=!1;n<u&&!1===w;)!1===k[n]?(c[z].addEventListenerWithParams(ON_MOUSE_UP,this.returnPosition,this,c[z].getX(),c[z].getY(),z,c[z].getText(),n),c[z].setPosition(r[n].getX(),r[n].getY()),
h[n]=f,k[n]=!0,c[z].setExtraData("boxposition",n),c[z].setUsed(!0),w=!0):t++,n++;t=n}this.checkVictory()};this.checkVictory=function(){var f=0;for(e=0;e<u;e++)!0===k[e]&&f++;if(!(f<u)&&f===u){f=!0;for(e=0;e<u;e++)h[e]!==m.charAt(e)&&(f=!1);if(!0===f){F.alpha=0;F.visible=!0;s_oStage.setChildIndex(F,s_oStage.numChildren-1);createjs.Tween.get(F).to({alpha:1},700,createjs.Ease.cubicOut);D.setVisible(!0);s_oGame.stoppedTime(!0);playSound("guessed",1,!1);s_oGame.animEarnedMoney(u);for(e=0;e<NUM_OF_SPAWN_LETTER;e++)c[e].block(!0);
for(f=0;f<NUMBER_QUEST_IMAGE;f++)l[A][f].block(!0);$(s_oMain).trigger("end_level",{ilevel:A});v.block(!0);E.block(!0)}else C.alpha=0,C.visible=!0,s_oStage.setChildIndex(C,s_oStage.numChildren-1),createjs.Tween.get(C).to({alpha:1},700,createjs.Ease.cubicOut),!0===x&&(playSound("wrong",1,!1),x=!1)}};this.setLevel=function(f){A=f};this.showPicture=function(){l[A][0].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);!1===s_bMobile&&l[A][0].setCursorType("pointer");switch(NUMBER_QUEST_IMAGE){case 2:l[A][1].setPosition(CANVAS_WIDTH/
2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);l[A][1].setCursorType("pointer");break;case 3:l[A][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100);l[A][2].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+200);!1===s_bMobile&&(l[A][1].setCursorType("pointer"),l[A][2].setCursorType("pointer"));break;case 4:l[A][1].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-100),l[A][2].setPosition(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+
200),l[A][3].setPosition(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+200),!1===s_bMobile&&(l[A][1].setCursorType("pointer"),l[A][2].setCursorType("pointer"),l[A][3].setCursorType("pointer"))}for(e=0;4>e;e++)this.addEventForImage(e,0);u=m.length;var f=s_oSpriteLibrary.getSprite("letterbox"),z=f.width,n=CANVAS_WIDTH/2-z*u/2+z/2;for(e=0;e<u;e++)r[e]=new CGfxButton(s_oStage,n,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+470,f,!0),r[e].block(!0),k[e]=!1,n+=z};this.addEventForImage=function(f,z,n,w,M){0===
z&&l[A][f].addEventListenerWithParams(ON_MOUSE_UP,this.zoomImage,this,l[A][f].getX(),l[A][f].getY(),l[A][f].getScale(),f);1===z&&(l[A][f].setPosition(n,w),l[A][f].setScale(M),l[A][f].addEventListenerWithParams(ON_MOUSE_UP,this.zoomImage,this,n,w,M,f),q[A][f].setVisible(!1))};this.zoomImage=function(f,z,n,w){l[A][w].setPosition(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50);l[A][w].setScale(2);l[A][w].changeChildIndex(s_oStage.numChildren-5);l[A][w].addEventListenerWithParams(ON_MOUSE_UP,this.addEventForImage,
this,w,1,f,z,n);q[A][w].setVisible(!0);q[A][w].changeChildIndex(s_oStage.numChildren-4)};s_oGameSettings=this;this._init()}var s_oGameSettings;
function CGameOver(b){var g,d,m,l,q,e,r,k;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(k);$(s_oMain).trigger("save_score",s_oGame.getMoney());var c=createBitmap(s_oSpriteLibrary.getSprite("bg_gameover"));s_oStage.addChild(c);c=s_oSpriteLibrary.getSprite("money_panel");m=new CTextButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2,c,b,PRIMARY_FONT,"#ffffff",50,-8,s_oStage);m.block(!0);m.setScale(1);c=s_oSpriteLibrary.getSprite("but_menu");g=new CGfxButton(s_oStage,
CANVAS_WIDTH/2,CANVAS_HEIGHT/2+270,c);g.addEventListener(ON_MOUSE_UP,this._onButToMenuRelease,this);l=new CTLText(s_oStage,CANVAS_WIDTH/2-400,CANVAS_HEIGHT/2-270,800,136,136,"center","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1);l.setOutline(4);new CTLText(s_oStage,CANVAS_WIDTH/2-400,CANVAS_HEIGHT/2-270,800,136,136,"center","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_GAMEOVER,!0,!0,!1,!1);c=CANVAS_WIDTH/2-180;var u=CANVAS_HEIGHT/2-50;e=new CTLText(s_oStage,c-250,u,450,96,96,"right","#ff21fe",PRIMARY_FONT,
1,0,0,TEXT_SCORE,!0,!0,!1,!1);e.setOutline(4);q=new CTLText(s_oStage,c-250,u,450,96,96,"right","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_SCORE,!0,!0,!1,!1);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:0},1E3).call(function(){d.visible=!1})};this.unload=function(){m.unload();m=null;g.unload();g=null;s_oStage.removeChild(r,k,l,l,q,e);s_oGameOver=e=q=l=k=r=null};this._onButToMenuRelease=function(){$(s_oMain).trigger("show_interlevel_ad");
this.unload();s_oMain.gotoMenu()};s_oGameOver=this;this._init()}var s_oGameOver;
function CLanguageMenu(){var b,g,d,m,l,q,e,r,k,c,u,t,D,C,F,E,v,A,h=null,H=null;this._init=function(){E=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(E);var p=s_oSpriteLibrary.getSprite("logo_small");b=CANVAS_WIDTH/2-540+PADDING;g=CANVAS_HEIGHT/2-840+PADDING;v=createBitmap(p);v.x=b;v.y=g;v.regX=p.width/2;v.regY=p.height/2;s_oStage.addChild(v);F=new CTLText(s_oStage,CANVAS_WIDTH/2-500,CANVAS_HEIGHT/2-350,1E3,104,104,"right","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_SELECT_LANG,!0,!0,
!1,!1);F.setOutline(4);new CTLText(s_oStage,CANVAS_WIDTH/2-500,CANVAS_HEIGHT/2-350,1E3,104,104,"right","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_SELECT_LANG,!0,!0,!1,!1);p=s_oSpriteLibrary.getSprite("but_flag_it");k=new CGfxButton(s_oStage,CANVAS_WIDTH/2+350,CANVAS_HEIGHT/2-100,p);k.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,LANGUAGE_IT);p=s_oSpriteLibrary.getSprite("but_flag_en");c=new CGfxButton(s_oStage,CANVAS_WIDTH/2-350,CANVAS_HEIGHT/2-100,p);c.addEventListenerWithParams(ON_MOUSE_UP,
this._onButPlayRelease,this,LANGUAGE_EN);p=s_oSpriteLibrary.getSprite("but_flag_fr");u=new CGfxButton(s_oStage,CANVAS_WIDTH/2,CANVAS_HEIGHT/2-100,p);u.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,LANGUAGE_FR);p=s_oSpriteLibrary.getSprite("but_flag_es");t=new CGfxButton(s_oStage,CANVAS_WIDTH/2+350,CANVAS_HEIGHT/2+150,p);t.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,LANGUAGE_ES);p=s_oSpriteLibrary.getSprite("but_flag_ger");D=new CGfxButton(s_oStage,CANVAS_WIDTH/
2-350,CANVAS_HEIGHT/2+150,p);D.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,LANGUAGE_GER);p=s_oSpriteLibrary.getSprite("but_flag_por");C=new CGfxButton(s_oStage,CANVAS_WIDTH/2,CANVAS_HEIGHT/2+150,p);C.addEventListenerWithParams(ON_MOUSE_UP,this._onButPlayRelease,this,LANGUAGE_POR);p=s_oSpriteLibrary.getSprite("audio_icon");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(l=CANVAS_WIDTH-p.height/2-PADDING,q=p.height/2+PADDING,r=new CToggle(s_oStage,l,q,p,s_bAudioActive),r.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),d=l-p.width/2-10,m=q):(d=CANVAS_WIDTH-p.height/2-PADDING,m=p.height/2+PADDING);p=window.document;var x=p.documentElement;h=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;H=p.exitFullscreen||p.mozCancelFullScreen||p.webkitExitFullscreen||p.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(h=!1);h&&screenfull.isEnabled&&(p=s_oSpriteLibrary.getSprite("but_fullscreen"),A=new CToggle(s_oStage,d,m,p,s_bFullscreen,s_oStage),A.addEventListener(ON_MOUSE_UP,
this._onFullscreenRelease,this));e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){s_oStage.removeChild(e);e=null});!1===s_bMobile&&(r.setCursorType("pointer"),c.setCursorType("pointer"),t.setCursorType("pointer"),u.setCursorType("pointer"),D.setCursorType("pointer"),k.setCursorType("pointer"),C.setCursorType("pointer"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();
k=null;c.unload();c=null;u.unload();u=null;t.unload();t=null;D.unload();D=null;C.unload();v=F=C=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r.unload(),r=null;h&&screenfull.isEnabled&&A.unload();s_oStage.removeAllChildren();s_oLanguageMenu=null};this.refreshButtonPos=function(p,x){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(l-p,x+q);h&&screenfull.isEnabled&&A.setPosition(d-p,m+x);v.x=b+p;v.y=g+x};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this._onButPlayRelease=function(p){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame(p)};this.resetFullscreenBut=function(){h&&screenfull.isEnabled&&A.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?H.call(window.document):h.call(window.document.documentElement);sizeHandler()};s_oLanguageMenu=this;this._init()}var s_oLanguageMenu=null;
function CInterface(b){var g,d,m,l,q,e,r,k,c,u,t,D,C,F,E,v,A,h,H,p,x,f,z,n,w,M,G,O,P,U,T,W,Q=null,Z=null;this._init=function(){H=TIME_FOR_EVERY_WORD;p=!0;var a=s_oSpriteLibrary.getSprite("logo_small");m=CANVAS_WIDTH/2-540+PADDING;l=CANVAS_HEIGHT/2-840+PADDING;O=createBitmap(a);O.x=m;O.y=l;O.regX=a.width/2;O.regY=a.height/2;s_oStage.addChild(O);var I=s_oSpriteLibrary.getSprite("but_exit");r=CANVAS_WIDTH-I.height/2-PADDING;k=I.height/2+PADDING;t=new CGfxButton(s_oStage,r,k,I,!0);t.addEventListener(ON_MOUSE_UP,
this._onExit,this);a=CANVAS_WIDTH-I.width/2-10;!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(q=a-165-PADDING,e=I.height/2+PADDING,I=s_oSpriteLibrary.getSprite("audio_icon"),u=new CToggle(s_oStage,q,e,I,s_bAudioActive),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),g=q-I.width/2-10,d=e):(g=a-165-PADDING,d=I.height/2+PADDING);a=window.document;I=a.documentElement;Q=I.requestFullscreen||I.mozRequestFullScreen||I.webkitRequestFullScreen||I.msRequestFullscreen;Z=a.exitFullscreen||a.mozCancelFullScreen||
a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(Q=!1);Q&&screenfull.isEnabled&&(I=s_oSpriteLibrary.getSprite("but_fullscreen"),W=new CToggle(s_oStage,g,d,I,s_bFullscreen,s_oStage),W.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));a=s_oSpriteLibrary.getSprite("shadow");z=createBitmap(a);z.x=CANVAS_WIDTH/2;z.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT+50;z.regX=a.width/2;z.regY=a.height/2;s_oStage.addChild(z);v=new createjs.Container;v.x=CANVAS_WIDTH/2;v.y=CANVAS_HEIGHT/
2+GAME_ELEMENT_HEIGHT-370;s_oStage.addChild(v);a=s_oSpriteLibrary.getSprite("level_panel");E=createBitmap(a);E.regX=a.width/2;E.regY=a.height/2;v.addChild(E);F=new CTLText(v,-100,-65,200,120,60,"center","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_LEVEL+" 1",!0,!0,!0,!1);F.setOutline(6);C=new CTLText(v,-100,-65,200,120,60,"center","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_LEVEL+" 1",!0,!0,!0,!1);a=s_oSpriteLibrary.getSprite("money_panel");A=new CText(CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-340,a,b+TEXT_PT,
PRIMARY_FONT,"#ffffff",66,-10);s_oStage.addChild(x);!0===BONUS_TIME?(h=new CText(CANVAS_WIDTH/2+300,CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-340,a,H+"s",PRIMARY_FONT,"#ffffff",66,-10),s_oStage.addChild(f)):H=0;this.helpPanel();this.refreshButtonPos(s_iOffsetX,s_iOffsetY);!1===s_bMobile&&(t.setCursorType("pointer"),u.setCursorType("pointer"))};this.helpPanel=function(){var a=s_oSpriteLibrary.getSprite("bg_gameover");D=createBitmap(a);D.addEventListener("click",function(){});s_oStage.addChild(D);w=new CTLText(s_oStage,
CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2-250,600,600,60,"left","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_HELP,!0,!0,!0,!1);w.setOutline(4);n=new CTLText(s_oStage,CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2-250,600,600,60,"left","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_HELP,!0,!0,!0,!1);a=s_oSpriteLibrary.getSprite("but_next");P=new CGfxButton(s_oStage,CANVAS_WIDTH/2,CANVAS_HEIGHT/2+432,a);P.setScale(.7);P.addEventListener(ON_MOUSE_UP,this._onNextHelp2,this);0==s_bMobile&&P.setCursorType("pointer")};this._onNextHelp2=function(){P.unload();
P=null;this.helpPanel2()};this.helpPanel2=function(){var a=s_oSpriteLibrary.getSprite("but_next");P=new CGfxButton(s_oStage,CANVAS_WIDTH/2,CANVAS_HEIGHT/2+432,a);P.setScale(.7);P.addEventListener(ON_MOUSE_UP,this._onStartGame,this);0==s_bMobile&&P.setCursorType("pointer");w.unload();n.unload();a=CANVAS_WIDTH/2-300+80;var I=CANVAS_HEIGHT/2-150-115;w=new CTLText(s_oStage,a,I,600,300,60,"left","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_HELP2+COST_FOR_REMOVE_LETTERS+TEXT_PT,!0,!0,!0,!1);w.setOutline(4);n=new CTLText(s_oStage,
a,I,600,300,60,"left","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_HELP2+COST_FOR_REMOVE_LETTERS+TEXT_PT,!0,!0,!0,!1);I=CANVAS_HEIGHT/2-150+210;G=new CTLText(s_oStage,a,I,600,300,60,"left","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_HELP3+COST_OF_A_LETTER+TEXT_PT,!0,!0,!0,!1);G.setOutline(4);M=new CTLText(s_oStage,a,I,600,300,60,"left","#ff21fe",PRIMARY_FONT,1,0,0,TEXT_HELP3+COST_OF_A_LETTER+TEXT_PT,!0,!0,!0,!1);a=s_oSpriteLibrary.getSprite("but_remove_letters");T=createBitmap(a);T.x=CANVAS_WIDTH/2-320;T.y=CANVAS_HEIGHT/
2+210;T.regX=a.width/2;T.regY=a.height/2;s_oStage.addChild(T);a=s_oSpriteLibrary.getSprite("but_add_a_letter");U=createBitmap(a);U.x=CANVAS_WIDTH/2-320;U.y=CANVAS_HEIGHT/2-115;U.regX=a.width/2;U.regY=a.height/2;s_oStage.addChild(U)};this._onStartGame=function(){n.unload();w.unload();M.unload();G.unload();s_oStage.removeChild(D,U,T);P.unload();M=n=D=G=w=P=null;p=!1;T=U=null};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null;Q&&screenfull.isEnabled&&W.unload();s_oStage.removeChild(z);
z=null;t.unload();t=null;s_oStage.removeChild(v);v=null;A.unload();A=null;s_oStage.removeChild(x);x=null;s_oStage.removeChild(f);f=null;h.unload();h=null;s_oStage.removeChild(c);c=null;null!==D&&D.unload();s_oInterface=null};this.addedMoneyAnim=function(a,I,Y){0<a?(Y=new createjs.Text("+"+a,"bold 66px "+PRIMARY_FONT,Y),a=new createjs.Text("+"+a,"bold 66px "+PRIMARY_FONT,"#ffffff")):(Y=new createjs.Text(a,"bold 66px "+PRIMARY_FONT,Y),a=new createjs.Text(a,"bold 66px "+PRIMARY_FONT,"#ffffff"));Y.textAlign=
"center";Y.textBaseline="alphabetic";a.textAlign="center";a.textBaseline="alphabetic";a.outline=4;var R=new createjs.Container;R.x=CANVAS_WIDTH/2-150;R.y=CANVAS_HEIGHT/2+GAME_ELEMENT_HEIGHT-330;R.addChild(Y,a);s_oStage.addChild(R);createjs.Tween.get(R).to({y:CANVAS_HEIGHT/2-500},I);createjs.Tween.get(R).to({alpha:0},I).call(function(){s_oStage.removeChild(R);R=null})};this.setStoppedTime=function(a){p=a};this.resetCounter=function(){H=TIME_FOR_EVERY_WORD;h.setText(H+"s")};this.refreshButtonPos=function(a,
I){t.setPosition(r-a,I+k);O.x=m+a;O.y=l+I;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(q-a,I+e);Q&&screenfull.isEnabled&&W.setPosition(g-a,d+I)};this.refreshMoney=function(a){A.setText(a+"PT")};this.refreshNuMLevel=function(a){a+=1;C.refreshText(TEXT_LEVEL+" "+a);F.refreshText(TEXT_LEVEL+" "+a)};this.getCount=function(){return Math.round(H)};this.update=function(){0<H&&!1===p&&(H-=1/createjs.Ticker.framerate,h.setText(Math.round(H)+"s"))};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=
function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){Q&&screenfull.isEnabled&&W.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?Z.call(window.document):Q.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CText(b,g,d,m,l,q,e,r){var k,c,u;this._init=function(t,D,C,F,E,v,A){var h=createBitmap(C),H=Math.ceil(A/20);u=new createjs.Text(F,"bold "+A+"px "+E,"#000000");u.textAlign="center";u.textBaseline="alphabetic";var p=u.getBounds();u.x=C.width/2+H;u.y=Math.floor(C.height/2+p.height/3+H)+r;u.alpha=.5;c=new createjs.Text(F,"bold "+A+"px "+E,v);c.textAlign="center";c.textBaseline="alphabetic";p=c.getBounds();c.x=C.width/2;c.y=Math.floor(C.height/2+p.height/3)+r;k=new createjs.Container;k.x=t;k.y=
D;k.regX=C.width/2;k.regY=C.height/2;k.addChild(h,u,c);s_oStage.addChild(k);this._initListener()};this._initListener=function(){oParent=this};this.setText=function(t){c.text=t;u.text=t};this.changeChildIndex=function(t){null!==d?s_oStage.setChildIndex(k,t):s_oStage.setChildIndex(c,t)};this.setVisible=function(t){k.visible=t};this.unload=function(){s_oStage.removeChild(k)};this._init(b,g,d,m,l,q,e);return this}
function CCreditsPanel(){var b,g,d,m,l,q,e,r,k;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(m);r=new createjs.Shape;r.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=.01;d=r.on("click",this._onLogoButRelease);s_oStage.addChild(r);var c=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-c.height/2-PADDING;g=c.height/2+PADDING;q=new CGfxButton(s_oStage,b,g,c,s_oStage);q.addEventListener(ON_MOUSE_UP,this.unload,this);
e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"60px "+PRIMARY_FONT,"#ff21fe");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-180+60;s_oStage.addChild(e);c=s_oSpriteLibrary.getSprite("logo_ctl");l=createBitmap(c);l.regX=c.width/2;l.regY=c.height/2;l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2;s_oStage.addChild(l);k=new createjs.Text("www.codethislab.com","60px "+PRIMARY_FONT,"#ff21fe");k.textAlign="center";k.textBaseline="alphabetic";k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/
2+180;s_oStage.addChild(k);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(c,u){q.setPosition(b-c,u+g)};this.unload=function(){r.off("click",d);q.unload();q=null;s_oStage.removeChild(m);s_oStage.removeChild(l);s_oStage.removeChild(r);s_oStage.removeChild(k);s_oStage.removeChild(e);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){window.open("https://www.codethislab.com/","_blank")};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var b=this._iStartingFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(b--,this._oText.font=b+"px "+this._szFont,this._oText.lineHeight=Math.round(b*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>b););this._iFontSize=b}},__verticalAlign:function(){if(this._bVerticalAlign){var b=this._oText.getBounds().height;
this._oText.y-=(b-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(b){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=
new createjs.Text(b,this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(b)},setY:function(b){this._y=b;this._oText.y=b;this._oDebugShape&&(this._oDebugShape.y=b-this._iHeight)},setVerticalAlign:function(b){this._bVerticalAlign=b},setOutline:function(b){null!==this._oText&&(this._oText.outline=b)},setShadow:function(b,g,d,m){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(b,g,d,m))},setColor:function(b){this._oText.color=b},setAlpha:function(b){this._oText.alpha=b;this._oDebugShape&&(this._oDebugShape.alpha=b)},unload:function(){this._oContainer.removeChild(this._oText);
this._bDebug&&this._oContainer.removeChild(this._oDebugShape)},setFontSize:function(b){this._iFontSize=this._iStartingFontSize=b;this.refreshText(this._oText.text)},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getMsg:function(){return this._oText.text},getX:function(){return this._x},getY:function(){return this._y},getColor:function(){return this._oText.color},getFontSize:function(){return this._iFontSize},refreshText:function(b){""===b&&
(b=" ");null===this._oText&&this.__createText(b);this._oText.text=b;this._oText.font=this._iStartingFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iStartingFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(b,g,d,m,l,q,e,r,k,c,u,t,D,C,F,E,v){this._oContainer=b;this._x=g;this._y=d;this._iWidth=m;this._iHeight=l;this._bMultiline=E;this._iStartingFontSize=this._iFontSize=q;this._szAlign=e;this._szColor=r;this._szFont=k;this._iPaddingH=u;this._iPaddingV=t;this._bVerticalAlign=F;this._bFitText=C;this._bDebug=v;this._oDebugShape=null;this._fLineHeightFactor=c;this._oText=null;D&&this.__createText(D)}
function extractHostname(b){b=-1<b.indexOf("://")?b.split("/")[2]:b.split("/")[0];b=b.split(":")[0];return b=b.split("?")[0]}function extractRootDomain(b){b=extractHostname(b);var g=b.split("."),d=g.length;2<d&&(b=g[d-2]+"."+g[d-1]);return b}
var getClosestTop=function(){var b=window,g=!1;try{for(;b.parent.document!==b.document;)if(b.parent.document)b=b.parent;else{g=!0;break}}catch(d){g=!0}return{topFrame:b,err:g}},getBestPageUrl=function(b){var g=b.topFrame,d="";if(b.err)try{try{d=window.top.location.href}catch(l){var m=window.location.ancestorOrigins;d=m[m.length-1]}}catch(l){d=g.document.referrer}else d=g.location.href;return d},TOPFRAMEOBJ=getClosestTop(),PAGE_URL=getBestPageUrl(TOPFRAMEOBJ);
function seekAndDestroy(){for(var b=extractRootDomain(PAGE_URL),g=[String.fromCharCode(99,111,100,101,116,104,105,115,108,97,98,46,99,111,109),String.fromCharCode(101,110,118,97,116,111,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,99,111,109),String.fromCharCode(99,111,100,101,99,97,110,121,111,110,46,110,101,116)],d=0;d<g.length;d++)if(g[d]===b)return!0;return!0};
