function m(b,a,c,d){b.s.jb(b.ob,a,c,d)}function n(b,a,c,d){b.s.ea?m(b,a,c,d):b.s.Ne()._OnMessageFromDOM({type:"event",component:b.ob,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.s.B(b.ob,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}function v(b){b.Tb||(b.s.xc(b.ce),b.Tb=!0)}window.Gb=class{constructor(b,a){this.s=b;this.ob=a;this.Tb=!1;this.ce=()=>this.Oa()}hd(){}Oa(){}};
window.Af=class{constructor(){this.dd=-1}j(){-1!==this.dd&&(self.clearTimeout(this.dd),this.dd=-1)}};"use strict";function ba(b,a){q(b,"get-element",c=>{const d=w(b,c.elementId);return a(d,c)})}function w(b,a){b=b.Ta.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Rb}
window.md=class extends self.Gb{constructor(b,a){super(b,a);this.Ta=new Map;this.mb=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=w(this,c);this.mb&&d.parentElement.removeChild(d);this.Ta.delete(c)}],["set-visible",c=>{if(this.mb){var d=this.Ta.get(c.elementId),e=d.Rb;d.Md?e.style.display=c.isVisible?"":"none":d.ff=!!c.isVisible}}],["update-position",c=>{if(this.mb){var d=this.Ta.get(c.elementId),e=d.Rb,f=this.s;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.lf=g;g=f.od(g);g!==d.Fa&&(e.remove(),f.qc(g).appendChild(e),d.Fa=g,f.Gc());c=c.htmlZIndex;c!==d.Oc&&(d.Oc=c,f.Gc());d.Md||(d.Md=!0,d.ff&&(e.style.display=""))}}],["update-state",c=>{w(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=w(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let da=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.qf?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.uf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ea(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let z=new Audio;
const fa={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ha(b){b=await ia(b);return(new TextDecoder("utf-8")).decode(b)}
function ia(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ja=0;const ka=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ka.push(b)};const la=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.Kb=class b{constructor(a){this.ea=a.wf;this.wa=null;this.aa="";this.ab=a.tf;this.Eb={};this.Va=this.ta=null;this.Sa=[];this.na=null;this.Qd=!0;this.M=[];this.Yc=[];this.Zc=!1;this.de=()=>this.Le();this.Qc=!1;this.Jd=0;this.tb=null;this.$a=-1;this.kf=()=>this.We();this.Bb=new Set;this.ed=null;this.ee=[];this.A=a.fe;this.Ub="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ea=!1;if("cordova"===this.A&&this.ea&&x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ea=!1)}this.Ma()?self.chrome.webview.addEventListener("message",c=>this.yd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.yd(c));this.Xb=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.$e(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Re());this.B("runtime","cordova-fetch-local-file",c=>this.Se(c));this.B("runtime","create-job-worker",()=>this.Te());this.B("runtime","send-wrapper-extension-message",c=>this.Ze(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.wd(a)):this.wd(a)}j(){this.yc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Va&&(this.Va.j(),this.Va=null);for(const {canvas:a,
cb:c}of this.M)a.remove(),c.remove();this.M.length=0}xe(){return this.M[0].canvas}od(a){return Math.min(a,this.M.length-1)}qc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].cb}Be(){return ca&&"cordova"===this.A}Ib(){const a=navigator.userAgent;return ca&&la.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ze(){return x}pd(){return x&&la.has(this.A)}rd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Ma(){return this.rd()||"xbox-uwp-webview2"===this.A}async wd(a){this.ea&&!await ea()&&(this.ea=!1);"macos-wkwebview"===this.A?this.kb({type:"ready"}):this.Ma()&&(this.bf(),this.ee=(await this.Qe()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.Xb={};await this.Ie();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Xb.hasOwnProperty(c)?a.bb[d]={qf:!0,uf:this.Xb[c]}:this.qa.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.qa[c]))}a.lc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.xc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.sf?this.aa=a.sf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.yf&&(this.Eb=a.yf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ve(d));this.tb=
new self.Ce(this);await pa(this.tb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ea?await this.Pe(a,c.port2):await this.Oe(a,c.port2)}Ac(a){a=this.Eb.hasOwnProperty(a)?this.Eb[a]:a.endsWith("/workermain.js")&&this.Eb.hasOwnProperty("workermain.js")?this.Eb["workermain.js"]:"playable-ad"===
this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Ub)return a=await this.Fb(d.pf?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}ha(){return Math.max(window.innerWidth,1)}ba(){return Math.max(window.innerHeight,1)}vd(a){var c=this.aa,d=location.href,e=this.ha(),f=this.ba(),g=window.devicePixelRatio,h=b.hb(),k=a.Df,l=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.fe;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.tb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Cf,jobScheduler:{inputPort:A.Pc,outputPort:A.Xc,maxNumWorkers:A.gf},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ab+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.Be(),isiOSWebView:this.Ib(),isWindowsWebView2:this.rd(),isAnyWebView2Wrapper:this.Ma(),wrapperComponentIds:this.ee,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Pe(a,c){const d=this.Ac(a.xf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.oc(d,this.aa,{type:"module",name:"Runtime",pf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,cb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.lc||[],k=a.bb;h=await Promise.all(h.map(l=>this.Pa(l)));k=await Promise.all(k.map(l=>this.Pa(l)));if("cordova"===this.A)for(let l=0,p=a.kc.length;l<p;++l){const r=
a.kc[l],t=r[0];if(t===a.fd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Pa(t)}this.ta.postMessage(Object.assign(this.vd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.kc,mainProjectScript:a.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...qa(this.tb)]);this.Sa=E.map(l=>new l(this));this.ud();H(e);ra(g);sa(this.na);self.c3_callFunction=(l,p)=>{var r=this.na;return r.s.sd(r.ob,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.jb("runtime","go-to-last-error-script"))}async Oe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,cb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Sa=E.map(h=>new h(this));this.ud();H(d);ra(e);e=a.bb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.lc)){var f=[...a.lc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Pa(h)));await Promise.all(e.map(h=>y(h)));e=self.C3_ProjectScriptsStatus;f=a.fd;const g=a.kc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Pa(k),await y(k),"preview"!==this.A||e[h]||this.Ad(h,"main script did not run to completion")}catch(l){this.Ad(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Pa(k),await y(k);"preview"===this.A&&"object"!==typeof self.zf.Bf?(this.Nb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.vd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ka}),sa(this.na),this.xd(),this.Va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Va,
a))}Ad(a,c){this.Nb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}xd(){this.Nb()}Nb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Te(){const a=await ta(this.tb);return{outputPort:a,transferables:[a]}}$e(a){if(!this.Qc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,cb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Qd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Qd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,cb:p}=this.M.pop();p.remove();this.ea&&!d?this.Yc.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.ea?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,H(c),ra(d),this.M.push({canvas:c,cb:d});for(const l of this.Sa)if(l instanceof window.md&&l.mb)for(const p of l.Ta.values())e=l.s.od(p.lf),f=p.Fa,-1!==e&&-1!==f&&e!==f&&(f=p.Rb,f.remove(),l.s.qc(e).appendChild(f),p.Fa=e);this.Gc();return{addedCanvases:a,transferables:k}}Re(){for(const a of this.Yc)a.remove();this.Yc.length=0}Gc(){this.Zc||(this.Zc=!0,this.xc(this.de))}Le(){this.zd(this.de);
this.Zc=!1;let a=[];for(var c of this.Sa)if(c instanceof window.md){var d=c.mb?[...c.Ta.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Fa,l=h.Fa;return k!==l?k-l:g.Oc-h.Oc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Fa!==c&&(this.td(c,a.slice(d,e)),c=g.Fa,d=e)}d<e&&this.td(c,a.slice(d,e))}td(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Rb);var d=new Set(c);a=this.qc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Ne(){if(this.ea)throw Error("not available in worker mode");return this.Va}jb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}sd(a,c,d,e,f){const g=ja++,h=new Promise((k,l)=>{G.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ue(a);if("result"===c)this.Xe(a);else if("runtime-ready"===c)this.Ye();else if("alert-error"===c)this.Nb(),alert(a.message);else if("creating-runtime"===c)this.xd();else throw Error(`unknown message '${c}'`);}Ue(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Mb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Mb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Mb(f,!1,""+h)}):this.Mb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Mb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Xe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}B(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static mc(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}ud(){for(const a of this.Sa)if("runtime"===a.ob){this.na=a;return}throw Error("cannot find runtime DOM handler");}Ve(a){this.jb("debugger","message",a)}Ye(){for(const a of this.Sa)a.hd()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||oa)}static Bd(a){oa=!!a}xc(a){this.Bb.add(a);
this.Fc()}zd(a){this.Bb.delete(a);0===this.Bb.size&&this.yc()}Fc(){-1===this.$a&&0<this.Bb.size&&(this.$a=requestAnimationFrame(this.kf))}yc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}We(){this.$a=-1;for(const a of this.Bb)a();this.Fc()}Da(a){this.na.Da(a)}Na(a){this.na.Na(a)}Ec(){this.na.Ec()}Lb(a){this.na.Lb(a)}Ae(){return!!fa["audio/webm; codecs=opus"]}async cf(a){a=await this.sd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ee(a){this.Qc=!0;this.Jd=
a}ye(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}qd(a){return!this.ye(a)}async Pa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Ub&&this.qd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Se(a){const c=a.filename;switch(a.as){case "text":return await this.we(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");
}}ld(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async we(a){a=await this.ld(a);return await ha(a)}zc(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.Je(a.filename,a.vf,a.nf)}}Fb(a){return new Promise((c,d)=>{B.push({filename:a,vf:e=>{D--;this.zc();c(e)},nf:e=>{D--;this.zc();d(e)}});this.zc()})}async Je(a,c,d){try{const e=await this.ld(a),f=await ia(e);c(f)}catch(e){d(e)}}yd(a){if("entered-fullscreen"===
a)b.Bd(!0),I(this.na);else if("exited-fullscreen"===a)b.Bd(!1),I(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.ed(a),this.ed=null):"extension-message"===c?this.jb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ze(a){this.kb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}kb(a){this.Ma()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}bf(){window.moveTo=(a,c)=>{this.kb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.kb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Qe(){return this.Ma()?new Promise(a=>{this.ed=a;this.kb({type:"wrapper-init"})}):Promise.resolve()}async Ie(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.He(c,d));
await Promise.all(a)}async He(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Xb[a]=c.str;else{let d=await this.Me(c);d||(d=this.Ke(c));this.qa[a]=d}}async Me(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ke(a){a=this.af(a);return this.Ge(a.data,
a.rf)}af(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{rf:a,data:d}}Ge(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.Kb,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},wa={dispatchRuntimeEvent:!0};function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Ba(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Da=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Da.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ea(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ga=!1;document.addEventListener("pause",()=>Ga=!0);document.addEventListener("resume",()=>Ga=!1);function H(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function ra(b){b.addEventListener("selectstart",Ea);b.addEventListener("gesturehold",Ea);b.addEventListener("touchstart",Ea)}function sa(b){b.Id=!0;b.Tc=b.s.ha();b.ub=b.s.ba()}
function I(b){if(!b.la){var a=J.hb();a&&"any"!==b.bd&&Ha(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ha(),innerHeight:b.ba()})}}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ma(b){self.setTimeout(()=>{b.Hd=!0},1E3);"cordova"===b.s.A?(document.addEventListener("pause",()=>Na(b,!0)),document.addEventListener("resume",()=>Na(b,!1))):document.addEventListener("visibilitychange",()=>Na(b,"hidden"===document.visibilityState));b.ac=!("hidden"!==document.visibilityState&&!Ga);return{isSuspended:b.ac}}
function Oa(b){b.Dd||(b.Dd=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Pa(b){b.Cd||(b.Cd=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Qa(b){await xa(b.url)}
function Ra(b,a){b.Kd=a.message;-1===b.Kc&&(b.Kc=setTimeout(()=>{b.Kc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Kd)},250))}function Sa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.hb(),innerWidth:b.ha(),innerHeight:b.ba()})}
function Na(b,a){b.ac!==a&&((b.ac=a)?b.s.yc():b.s.Fc(),m(b,"visibilitychange",{hidden:a}),!a&&b.s.Ib()&&(-1!==b.ya&&clearTimeout(b.ya),Ta(b,b.ha(),b.ba(),0),document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0))}
function Ua(b,a,c){"Backspace"===c.key&&M(c);if(b.s.Ma()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.la||(d=ua.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.Vc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Vc=c.buttons)}}function Va(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Aa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Aa=a))}}
function Ta(b,a,c,d){const e=b.ha(),f=b.ba();b.ya=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb()}):10>d&&Wa(b,e,f,d+1)}function Wa(b,a,c,d){-1!==b.ya&&clearTimeout(b.ya);b.ya=setTimeout(()=>Ta(b,a,c,d),48)}
function Ha(b){b=b.bd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.mc(class extends self.Gb{constructor(b){super(b,"runtime");this.Id=!1;this.ya=-1;this.bd="any";this.ac=this.Cd=this.Dd=!1;this.hc=document.createElement("div");this.hc.className="c3-screen-reader-text";this.hc.setAttribute("aria-live","polite");document.body.appendChild(this.hc);this.Ha=null;this.la=!1;this.Kd="";this.Kc=-1;this.Hd=!1;this.Tc=b.ha();this.ub=b.ba();this.Aa=this.Db=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ia(c));b.B("runtime","raster-svg-image",c=>Ja(c));b.B("runtime","get-svg-image-size",c=>Ka(c));b.B("runtime","set-target-orientation",c=>{this.bd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>La(c));b.B("runtime","go-to-script",c=>La(c));b.B("runtime","before-start-ticking",()=>Ma(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var d=this.Ha;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ha&&(this.Ha.style.display="none")});b.B("runtime","enable-device-orientation",()=>Oa(this));b.B("runtime","enable-device-motion",()=>Pa(this));b.B("runtime","add-stylesheet",c=>Qa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.hc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.s.xe().style.display="";this.s.Ee(c.duration)});b.B("runtime","export-to-video-progress",c=>Ra(this,c));b.B("runtime","exported-to-video",c=>{window.mf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.mf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ba(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.Vc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Id){var c=this.ha();var d=this.ba();if(this.s.pd()){if(this.Hd){if(this.Tc===
c&&d<this.ub){this.Db=this.ub-d;Va(this,this.ub,this.Db);c=void 0;break a}0<this.Db&&(this.Db=0,Va(this,d,this.Db))}this.Tc=c;this.ub=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.hb()});this.s.Ib()&&(-1!==this.ya&&clearTimeout(this.ya),Ta(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Sa(this,c));window.addEventListener("webkitfullscreenerror",c=>Sa(this,c));window.addEventListener("mozfullscreenerror",c=>Sa(this,c));if(b.Ib()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ba(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Wa=new Set;this.Zb=new WeakSet;this.va=!1}hd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,wa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},wa);this.Vc=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||Ba(a))&&m(this,"keyboard-blur",null,wa)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,va));window.addEventListener("mousemove",a=>N(this,"mousemove",a,va));window.addEventListener("mouseup",a=>N(this,"mouseup",a,va));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Aa,pageX:a.pageX,pageY:a.pageY+this.Aa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Xa(a.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.s.ea&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Ec();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.s.ze()&&!this.s.pd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ba(),navigator.virtualKeyboard.boundingRect.height)}))}ha(){return this.s.ha()}ba(){return this.s.ba()}Ec(){var b=[...this.Wa];this.Wa.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Zb.has(a)||this.Wa.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");this.Zb.delete(b);
let a;try{a=b.play()}catch(c){this.Wa.add(b);return}a&&a.catch(()=>{this.Zb.has(b)||this.Wa.add(b)})}Na(b){this.Wa.delete(b);this.Zb.add(b)}Lb(b){this.va=!!b}});"use strict";async function pa(b){if(b.df)throw Error("already initialised");b.df=!0;var a=b.xa.Ac(("playable-ad"===b.xa.A?b.xa.ab:"")+"dispatchworker.js");b.Jc=await b.xa.oc(a,b.nb,{name:"DispatchWorker"});a=new MessageChannel;b.Pc=a.port1;b.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Xc=await ta(b)}
function qa(b){return[b.Pc,b.Xc]}async function ta(b){const a=b.Rd.length;var c=b.xa.Ac(("playable-ad"===b.xa.A?b.xa.ab:"")+"jobworker.js");c=await b.xa.oc(c,b.nb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Rd.push(c);return e.port1}
self.Ce=class{constructor(b){this.xa=b;this.nb=b.aa;this.nb="preview"===b.A?this.nb+"workers/":this.nb+b.ab;this.gf=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Rd=[];this.Xc=this.Pc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Kb({wf:!0,xf:"workermain.js",bb:["scripts/c3runtime.js"],kc:[],fd:"",tf:"scripts/",lc:[],fe:"html5"}));"use strict";
async function Ya(b,a){a=a.type;let c=!0;0===a?c=await Za():1===a&&(c=await $a());m(b,"permission-result",{type:a,result:c})}async function Za(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function $a(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Kb.mc(class extends self.Gb{constructor(b){super(b,"touch");q(this,"request-permission",a=>Ya(this,a))}});"use strict";const ab=180/Math.PI;
async function bb(b,a){if(a.isiOSCordova||a.isSafari)b.cc=!0;b.cd=a.timeScaleMode;b.Wd=["equalpower","HRTF","soundfield"][a.panningModel];b.Gd=["linear","inverse","exponential"][a.distanceModel];b.Xd=a.refDistance;b.Vd=a.maxDistance;b.Zd=a.rolloffFactor;if(b.s.Qc)b.cc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Jd)});else{var c={latencyHint:a.latencyHint};b.be||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");cb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&cb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ra=b.g.createGain();b.Ra.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function db(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Sd=g.slice(0);fb(b,g);try{b.R=await gb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(u.sb){hb(u,p.x,p.y,p.z,p.angle);var C=self.eb.Fe;u.ra[0]!==C(A)&&
(u.ra[0]=C(A),u.F.coneInnerAngle=C(A));u.ra[1]!==C(ma)&&(u.ra[1]=C(ma),u.F.coneOuterAngle=C(ma));u.ra[2]!==na&&(u.ra[2]=na,u.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),ib(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(ub){console.error("[Construct] Audio: error starting playback: ",ub);return}finally{c=g.join(" ");d=b.Ab.get(c);if(!d)throw Error("expected pending tag");d.gd--;0===d.gd&&(d.resolve(),b.Ab.delete(c))}v(b)}
async function jb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await kb(b,c);for(const h of S(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ua=g;h.ae=a}T(b)}async function lb(b,a){const c=a.tags;a=a.rate;await kb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Ea())}async function mb(b,a){const c=a.tags;a=a.pos;await kb(b,c);for(const d of S(b,c))d.uc(a)}
async function nb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await gb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ob(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function pb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.le(b,...e);else if("delay"===c)d=new self.je(b,...e);else if("convolution"===c){var g=d=new self.ie(b,f.ia,...e),h=a.bufferType;g.Ed=a.bufferOriginalUrl;g.Fd=h}else if("flanger"===c)d=
new self.me(b,...e);else if("phaser"===c)d=new self.oe(b,...e);else if("gain"===c)d=new self.ne(b,...e);else if("stereopan"===c)d=new self.qe(b,...e);else if("tremolo"===c)d=new self.re(b,...e);else if("ringmod"===c)d=new self.pe(b,...e);else if("distortion"===c)d=new self.ke(b,...e);else if("compressor"===c)d=new self.he(b,...e);else if("analyser"===c)d=new self.ge(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Pd=l.length;d.ad=
h;l.push(d);qb(g,h)}rb(b)}
async function sb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.ic=a.timeScale;b.Lc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.va=a.isSilent;b.s.Lb(b.va);b.Yb=a.masterVolume;b.Ra.gain.value=
b.Yb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>pb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>tb(b,f,c)));T(b)}
async function vb(b,a){try{const c=b.g.suspend(a.time);b.Od?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.jb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>wb(d)),b.Od=!0);await c}catch(c){wb(c)}}
function cb(b){b.Sb||(b.Nc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Sb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.gb()===c)return await xb(g),g;if(f)return null;if(e&&(b.cc||b.Nd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Ba()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.be;e&&f&&(b.Nd=!0);c=!e||b.cc||f?new self.ue(b,a,c,d,e,f):new self.se(b,a,c,d,e);b.ja.push(c);await xb(c);b.Ud.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Ud.add(a));return c}
function yb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function zb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.fa()}function qb(b,a){a=a.toLowerCase();let c=b.fa();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Ab(b,a))d=c,e=f.da||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Uc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Ab(b,a){if(a)for(const c of b.H)yb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Bb(b,a,c){return c?b.s.cf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Cb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(yb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function gb(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.nc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Hc?new self.te(a.u,a,e):new self.ve(a.u,a,e);b.H.push(e);return e}
function fb(b,a){a=a.join(" ");let c=b.Ab.get(a);if(!c){let d=null;c={gd:0,promise:new Promise(e=>d=e),resolve:d};b.Ab.set(a,c)}c.gd++}function kb(b,a){return(b=b.Ab.get((0===a.length?b.Sd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Qa.size)v(b);else for(const a of b.H)if(!a.I&&!a.O()){v(b);break}}function Db(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function rb(b){b.Rc||(b.Rc=!0,Promise.resolve().then(()=>Eb(b)))}
function Eb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.fb());m(b,"fxstate",{fxstate:a});b.Rc=!1}
async function tb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await gb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],f=d.orient,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],e.setPosition(...b.Ya),e.setOrientation(...b.Xa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),ib(b,d));c.Play(k,l,p,0);a.isPlaying||c.ib();c.Cc(a)}}}function wb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.Gb{constructor(b){super(b,"audio");this.Ra=this.g=null;this.Sb=this.Nc=!1;this.za=()=>{if(!this.Nc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Nc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Sb=!1)}};this.ja=[];this.H=[];this.R=null;this.Sd=[];this.Ud=new Set;this.Td=-1;this.Ab=new Map;this.Yb=1;this.va=!1;this.cd=0;this.ic=1;this.Lc=0;this.Wd="HRTF";this.Gd="inverse";this.Xd=600;this.Vd=1E4;this.Zd=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Nd=this.cc=!1;this.be=this.s.Ae();this.ka=new Map;this.Qa=new Set;this.Od=this.Rc=!1;this.Uc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Uc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(zb(this,this.Uc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Ra.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>bb(this,a)],["play",a=>db(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ib():d.Jb();T(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>jb(this,a)],["set-master-volume",a=>{this.Yb=a.vol;this.Ra.gain.value=this.Yb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Fb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.s.Lb(this.va);for(const c of this.H)c.Ob()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.vc(a)}],["set-playback-rate",a=>lb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),ib(d,a)}],["seek",a=>mb(this,a)],["preload",a=>nb(this,a)],["unload",a=>ob(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.wc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>pb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);rb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);qb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Lc=a.gameTime;this.Td=a.tickCount;if(0!==this.cd)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&hb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>sb(this,a)],["offline-render-audio",a=>vb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Ra}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Hb(){return this.va}Da(b){this.s.Da(b)}Na(b){this.s.Na(b)}Oa(){for(var b of this.Qa)b.Oa();
b=this.g.currentTime;for(var a of this.H)a.Oa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());m(this,"state",{tickCount:this.Td,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Qa].map(c=>({tag:c.ad,index:c.Pd,peak:c.Za,rms:c.Yd,binCount:c.l.frequencyBinCount,freqBins:c.Ld}))});0===a.length&&0===this.Qa.size&&this.Tb&&(this.s.zd(this.ce),this.Tb=!1)}static Fe(b){return b*ab}static nd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static De(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Kb.mc(self.eb);"use strict";function xb(b){b.Wb||(b.Wb=b.Bc());return b.Wb}self.jd=class{constructor(b,a,c,d,e){this.u=b;this.jf=a;this.Ja=c;this.T=d;this.ef=e;this.Hc="";this.Wb=null}j(){this.Wb=this.u=null}Bc(){}V(){return this.u.V()}rc(){return this.jf}gb(){return this.Ja}pc(){return this.T}Ba(){return this.ef}ga(){}};"use strict";
self.se=class extends self.jd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Hc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.vb=this.wb=null;this.L.addEventListener("canplaythrough",()=>!0);this.zb=this.V().createGain();this.yb=null;this.L.addEventListener("canplay",()=>{this.wb&&(this.wb(),this.vb=this.wb=null);!this.yb&&this.L&&(this.yb=this.V().createMediaElementSource(this.L),this.yb.connect(this.zb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.vb&&(this.vb(f),this.vb=this.wb=null)})}j(){Cb(this.u,this);this.zb.disconnect();this.zb=null;this.yb.disconnect();this.yb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Bc(){return new Promise((b,a)=>{this.wb=b;this.vb=a;this.L.src=this.Ja})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Hb(b){if(b.Ga)return b.Ga;var a=b.u.s;if("cordova"===a.A&&a.qd(b.Ja)&&a.Ub)b.Ga=await a.Fb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Ib(b){if(b.ia)return b.ia;b.ia=await Bb(b.u,b.Ga,b.hf);b.Ga=null}
self.ue=class extends self.jd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Hc="webaudio";this.ia=this.Ga=null;this.hf=!!f}j(){Cb(this.u,this);this.ia=this.Ga=null;super.j()}async Bc(){try{await Hb(this),await Ib(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Jb=0;
function Q(b,a){a=!!a;b.sb!==a&&(b.sb=a,b.sb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Wd,b.F.distanceModel=b.u.Gd,b.F.refDistance=b.u.Xd,b.F.maxDistance=b.u.Vd,b.F.rolloffFactor=b.u.Zd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function R(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(Q(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.fa())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.fa())))}function ib(b,a){b.Vb&&b.$c!==a&&(b.da.pan.value=a,b.$c=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ua=-1;b.G.gain.value=b.sc()}function Fb(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Ob())}
function hb(b,a,c,d,e){if(b.sb){var f=b.Ya,g=b.Xa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Sc?b.u.Lc:performance.now()/1E3}
self.kd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Pb=Jb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.sb=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.ra=[0,0,0];this.da=null;this.Vb=!1;this.$c=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ka=1;this.ua=!1;this.ma=1;b=this.u.cd;this.Sc=1===b&&!this.Ba()||2===b;this.Ua=this.pa=-1;this.ae=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}fa(){return zb(this.u,0<this.oa.length?this.oa[0]:"")}rc(){return this.P.rc()}gb(){return this.P.gb()}pc(){return this.P.pc()}Ba(){return this.P.Ba()}O(){}nc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}La(){}ga(){return this.P.ga()}Play(){}Ca(){}ib(){}Jb(){}Oa(b){-1!==this.Ua&&b>=this.Ua&&(this.Ua=-1,this.ae&&this.Ca(),Db(this.u,"fade-ended",this.oa,this.Pb))}sc(){const b=this.Ka;return isFinite(b)?b:0}Hb(){return this.u.Hb()}Ob(){}vc(){}Ea(){}uc(){}wc(){}tc(){}fb(){var b=
this.Pb,a=this.oa,c=this.ga(),d=-1===this.Ua?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ya,orient:this.Xa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.ma,uid:this.pa,bufferOriginalUrl:this.rc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.tc(),pan:f,stereoPan:this.da?
this.$c:null}}Cc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ea());Fb(this,b.isMuted)}};"use strict";
self.te=class extends self.kd{constructor(b,a,c){super(b,a,c);this.P.zb.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Ca();this.P.zb.disconnect();super.j()}W(){return this.P.W()}Dc(){this.I=!0;this.pa=-1;Db(this.u,"ended",this.oa,this.Pb)}O(){return this.W().ended}nc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.u.Da(d);this.J=this.I=!1;this.Y=b;this.ma=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Na(b);this.I=!0;this.J=!1;this.pa=-1}ib(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Na(b);this.J=!0}}Jb(){!this.J||this.I||this.O()||(this.u.Da(this.W()),this.J=!1)}Ob(){this.W().muted=this.ua||this.Hb()}vc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ea(){let b=this.ma;this.Sc&&(b*=this.u.ic);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}uc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}tc(){return this.La()}wc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Da(this.W()),this.sa=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.lb=null}
self.ve=class extends self.kd{constructor(b,a,c){super(b,a,c);this.o=null;this.$b=d=>this.Dc(d);this.Mc=!0;this.lb=null;this.S=this.bc=this.dc=0;this.Wc=1}j(){this.Ca();W(this);this.$b=null;super.j()}Dc(b){this.J||this.sa||b.target!==this.lb||(this.I=this.Mc=!0,this.pa=-1,W(this),Db(this.u,"ended",this.oa,this.Pb))}O(){return!this.I&&this.o&&this.o.loop||this.J?!1:this.Mc}nc(){return!this.o||this.I?!0:this.O()}La(){let b;b=this.J?this.S:this.bc+(V(this)-this.dc)*this.ma;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.ua=!1;this.Wc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ia;this.o.connect(this.G);this.lb=this.o;this.o.onended=this.$b;this.o.loop=b;this.o.start(d,c);this.J=this.I=this.Mc=!1;this.Y=b;this.ma=1;this.dc=V(this);this.bc=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}ib(){this.J||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.ga()),this.J=!0,this.o.stop(0))}Jb(){!this.J||this.I||this.O()||(W(this),
this.o=this.V().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,U(this,this.Ka),this.Ea(),this.o.start(0,this.S),this.dc=V(this),this.bc=this.S,this.J=!1)}sc(){return super.sc()*this.Wc}Ob(){this.Wc=this.ua||this.Hb()?0:1;U(this,this.Ka)}vc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ea(){let b=this.ma;this.Sc&&(b*=this.u.ic);this.o&&(this.o.playbackRate.value=b)}uc(b){this.I||this.O()||(this.J?this.S=b:(this.ib(),
this.S=b,this.Jb()))}tc(){return this.S}wc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.La(),this.Y&&(this.S%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,U(this,this.Ka),this.Ea(),this.o.start(0,this.S),this.dc=V(this),this.bc=this.S,this.sa=!1)}Cc(b){super.Cc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Pd=-1;this.T=this.ad="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.ad,params:this.m}}}
self.le=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.xb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.qb=X(this);this.qb.gain.value=c;this.v.connect(this.xb);this.v.connect(this.h);this.xb.connect(this.i);this.xb.connect(this.X);this.X.connect(this.qb);this.qb.connect(this.xb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.xb.disconnect();
this.X.disconnect();this.qb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.eb.nd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.qb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.ie=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Fd=this.Ed="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.pb=this.g.createConvolver();this.pb.normalize=c;this.pb.buffer=a;this.v.connect(this.pb);this.v.connect(this.h);this.pb.connect(this.i)}j(){this.v.disconnect();this.pb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.Ed;b.bufferUrl="";b.bufferType=this.Fd;return b}};
self.me=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.rb=X(this);this.rb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.rb);this.rb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.rb.gain,a/100,c,d)}}};
self.oe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.ne=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.nd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.qe=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.re=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.pe=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Cb=X(this);this.Cb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Cb.gain);this.C.start(0);this.v.connect(this.Cb);this.v.connect(this.h);this.Cb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Cb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.fc=X(this);this.ec=X(this);b=d;.01>b&&(b=.01);this.fc.gain.value=b;this.ec.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Ic=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ic[32768+e]=f,this.Ic[32768-
e-1]=-f;this.jc.curve=this.Ic;this.v.connect(this.fc);this.v.connect(this.h);this.fc.connect(this.jc);this.jc.connect(this.ec);this.ec.connect(this.i)}j(){this.v.disconnect();this.fc.disconnect();this.jc.disconnect();this.ec.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.he=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ge=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Ld=new Float32Array(this.l.frequencyBinCount);this.$d=new Uint8Array(a);this.Yd=this.Za=0;b=this.u;b.Qa.add(this);T(b)}j(){this.u.Qa.delete(this);this.l.disconnect();super.j()}Oa(){this.l.getFloatFrequencyData(this.Ld);this.l.getByteTimeDomainData(this.$d);const b=this.l.fftSize;let a=this.Za=0;for(var c=0;c<b;++c){let d=(this.$d[c]-
128)/128;0>d&&(d=-d);this.Za<d&&(this.Za=d);a+=d*d}c=self.eb.De;this.Za=c(this.Za);this.Yd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
